### ISSUE TITLE
Read values of datatype 5

### ISSUE THREAD

**Issue by Christian-Block** [eclipse/milo#100]
Hi,
i have a method to read different NodeIDs:
```
public DataValue readNode(NodeId nodeID) throws InterruptedException, ExecutionException {
    VariableNode node = client.getAddressSpace().createVariableNode(nodeID);
    DataValue value = node.readValue().get();
    return value;
}
```
My aim is to read the values as String or Integer. The most nodes are ok. But I have some nodes which have an other datatype e.g.:
System.out.println(ua.readNode("node").getValue());
    -->Variant{value=[4]}
System.out.println(ua.readNode("node").getValue().getDataType().hashCode());
    --> 5
System.out.println(ua.readNode("node").getValue().getValue().toString());
    --> [Lorg.eclipse.milo.opcua.stack.core.types.builtin.unsigned.UShort;@6a2b953e

How can i read values of datatype 5 or rather values in [*] ?

**Comment by kevinherron** [comment]
It looks like some of the nodes you're reading have either an array
datatype or in the case of "EGX_AktuellWirkleistung_ID4" the datatype is
UInt16.

Your client needs to be able to handle this. You can't request the server
return a different datatype for you.

Reading the DataType, ValueRank, and ArrayDimensions attributes should be
enough for your client to fully understand what the Value is might be.

**Comment by kevinherron** [comment]
Closing this for now. In the future this kind of question (versus reporting a bug) would be better suited for the mailing list: https://dev.eclipse.org/mailman/listinfo/milo-dev

Thanks!
