### ISSUE TITLE
Aggregate OPC UA Servers

### ISSUE THREAD

**Issue by Ox24** [eclipse/milo#105]
Is there an example of aggregating opc ua servers with this libary? 
Illustrated like this:

Client     Client    Client
   |             |            |
Aggregation Server
         |                  |
UA Server1 UA Server 2

So u can access data presented by any opc ua server from one server...

**Comment by kevinherron** [comment]
There's not an example. Aggregation is actually a lot of work to do right (I think...), and by the time the example was any good you'd practically have a product on your hands.

**Comment by Ox24** [comment]
Is there some example from the opc ua foundation? like something defined in their specification?

**Comment by kevinherron** [comment]
I'm not aware of anything, but that doesn't mean it doesn't exist :)

**Comment by Ox24** [comment]
Ok thx, maybe i try to implement one :)
