### ISSUE TITLE
Error 'BadTooManySessions' was returned during CreateSession

### ISSUE THREAD

**Issue by sangjiexun** [eclipse/milo#1068]
Error 'BadTooManySessions' was returned during CreateSession
![微信截图_20221020082915](https://user-images.githubusercontent.com/59449516/196844046-d8967ac9-d294-45fb-9bd2-b5ff41c673d1.png)
Excuse me, how to design and solve it

**Comment by kevinherron** [comment]
By default server is limited to 100 concurrent sessions. This server must already have a lot of clients connected.

You can increase the limit by overriding `OpcUaServerConfigLimits::getMaxSessionCount` and configuring this new limits object when you create a `OpcUaServerConfig`.

**Comment by kevinherron** [comment]
Yes, that's the override.... in this case you would need to make sure that the `SecureServer` instance is passed to `OpcUaServerConfigBuilder::setLimits` before the config is built.

**Comment by kevinherron** [comment]
The second screenshot is the "normal" approach - create a new `OpcUaServerConfigLimits` object with the desired changes, and then set that instance when building the config.
