### ISSUE TITLE
Will milo support pub/sub over AMQP/UDP?

### ISSUE THREAD

**Issue by tobiashaa** [eclipse/milo#109]
Hey there. When will milo support pub/sub? Thank you

https://opcfoundation.org/developer-tools/specifications-unified-architecture/part-14-pubsub/

**Comment by kevinherron** [comment]
I don't have a solid timeline I can provide. Once part 1.04 (which includes PubSub) is out of RC I'll start working on it, but even that's a lot of work. I think **best** case scenario is that it's ready to test in Nuremberg this November...

**Comment by CB-IT** [comment]
Are there any new information on this topic?

**Comment by kevinherron** [comment]
It's not happening soon. Milo is staying at OPC UA 1.03 while I push towards a 1.0 release.

OPC UA 1.04 will happen after that.

**Comment by ghalamif** [comment]
Hi, are there any updates on this topic?

**Comment by kevinherron** [comment]
@ghalamif slight progress... instead of "not planned", I have now done some background research and design work.

Maybe something this year?
