### ISSUE TITLE
Server: Unable to write to node of type "Variant"

### ISSUE THREAD

**Issue by ctron** [eclipse/milo#11]
I just tried writing a `String` to a Variable Node of Type `Variant`, which fails with "Bad Type".

Debugging into "AttributeWriter.validateDataType" it comes up with a `DataValue`, which gets unboxed to `Variant` and then to `String`. But then the check tries to assign a String to the target Variant, which fails of course.

I would expect that it is possible to write "anything" to a node of type `Variant`.

**Comment by kevinherron** [comment]
I'll have to look into whether that should be possible or not. You can write "anything" do a node of type `Variant` - you just have to encapsulate that anything in a `Variant` first.

**Comment by ctron** [comment]
That is what should happen .. at least I think it is.

So on the client side I am doing something like `write ( new DataValue ( new Variant ( "String" ) ) )`

On the server side it pops up like in the following screenshot:

![milo1](https://cloud.githubusercontent.com/assets/202474/16656515/4eeedf5c-445f-11e6-8fd4-871bc788eb0c.png)

So the original value is the DataValue, from there the Variant and then the String.

Or do you mean I should put a Variant inside the Variant?

**Comment by kevinherron** [comment]
You can't put a Variant in a Variant - I think you're right about this being a bug.

**Comment by ctron** [comment]
Yes I just saw that:

```java
checkArgument(clazzIsArray || !Variant.class.equals(componentClazz), "Variant cannot contain Variant");
```

**Comment by ctron** [comment]
Since it currently does block me, I can work on a fix if you like.

**Comment by kevinherron** [comment]
Sure, in that block you've breakpointed in, you'll need to add a check to see if expected is `Variant`, and if so, allow the write to proceed.

If you could start a unit test for AttributeWriter that would be good too - you could just test this case for now.

**Comment by ctron** [comment]
Alright then ... yes, you are right. A unit test seems to be a good way to start.
