### ISSUE TITLE
when the opc ua server quality stamp is bad, but the StatusCode in the DataValue received by the opc ua client is good.

### ISSUE THREAD

**Issue by armandxu** [eclipse/milo#1101]
why when the opc ua server quality stamp is bad, but the StatusCode in the DataValue received by the opc ua client is good.
<img width="651" alt="1674871185928" src="https://user-images.githubusercontent.com/7020744/215236276-244d43ca-d280-41a3-be27-a3d68e501c99.png">

<img width="875" alt="1674871124812" src="https://user-images.githubusercontent.com/7020744/215236249-eb3bb671-8755-4759-8b6d-7d674b008ddb.png">

_Originally posted by @armandxu in https://github.com/eclipse/milo/discussions/1100#discussioncomment-4801855_

**Comment by kimim** [comment]
As indicated in code:

```java
    private static String quality(StatusCode statusCode) {
        if (statusCode.isGood()) {
            return "good";
        } else if (statusCode.isBad()) {
            return "bad";
        } else if (statusCode.isUncertain()) {
            return "uncertain";
        } else {
            return "unknown";
        }
}
```

quality is just a string name for status code name.

I guess there is another field, you can get quality stamp from. But not from StatusCode.

**Comment by armandxu** [comment]
> As indicated in code: ```java private static String quality(StatusCode statusCode) { if (statusCode.isGood()) { return "good"; } else if (statusCode.isBad()) { return "bad"; } else if (statusCode.isUncertain()) { return "uncertain"; } else { return "unknown"; } } ``` quality is just a string name for status code name. I guess there is another field, you can get quality stamp from. But not from StatusCode.

I also don't think it's in StatusCode, but I can't find it in other components either.

**Comment by kevinherron** [comment]
I don’t know what I’m looking at in the UaExpert? screenshot, but are you sure you’re reading the same NodeId and the same Attribute? It looks like you might be reading DisplayName or Description in the 2nd picture instead of Value.

**Comment by armandxu** [comment]
> I don’t know what I’m looking at in the UaExpert? screenshot, but are you sure you’re reading the same NodeId and the same Attribute? It looks like you might be reading DisplayName or Description in the 2nd picture instead of Value.

**Comment by armandxu** [comment]
> re you sure you’re reading the same NodeId and the



> I don’t know what I’m looking at in the UaExpert? screenshot, but are you sure you’re reading the same NodeId and the same Attribute? It looks like you might be reading DisplayName or Description in the 2nd picture instead of Value.

hi，kevin，

**Comment by armandxu** [comment]
I found the problem, it is a bug in the opc server

**Comment by armandxu** [comment]
I found the problem, it is a bug in the opc server
