### ISSUE TITLE
Missing limits for StatusCode

### ISSUE THREAD

**Issue by jherkel** [eclipse/milo#1102]
OPC UA can report high and low limits within StatusCode.  I can extract this info manually but maybe it could be better if there was a method for that. Something like isLimitSet. Or is there any other way how to do it?

**Comment by kevinherron** [comment]
I'll leave this open as something to implement in the `dev/1.0` branch.

It seems like there's a few different methods for interpreting the InfoBits portion that could be useful.

For now you'll just have to create some utility functions in your project.
