### ISSUE TITLE
The matrix data in the writing operation cannot be set to a one-dimensional array

### ISSUE THREAD

**Issue by kdai319** [eclipse/milo#1109]
**Describe the bug**
When calling the write method on the client, changing a multidimensional array to a one-dimensional array may cause the current RPC request to fail. In this case the StatusCode.name will return “StatusCode{name=Bad_TypeMismatch, value=0x80740000, quality=bad}”

**Expected behavior**
in the uaExpert client, the same operation for the same node can be successful
Below is an operation screenshot of uaExpert ：
![ex1](https://user-images.githubusercontent.com/15166619/228122033-862e1db8-7179-45d9-bb01-f684cbce0310.png)
This is the original state of the node.
![ex2](https://user-images.githubusercontent.com/15166619/228122287-5f33cd64-8442-4ee8-b424-d5a42f549c14.png)
In UaExpert, you can set the dimension of the matrix, but I can't find the setting in milo's writing method. I'm not sure if I missed something, and there doesn't seem to be a similar case in the related tests...
![1765e63297ad49aa9fba06f8752f354](https://user-images.githubusercontent.com/15166619/228122639-7f299463-13eb-4bc1-ba94-8a400752bef7.png)
After setting the dimension as shown in the picture, the written data becomes a one-dimensional array.
![9fd1578edd00447f4b9700a0afc0da3](https://user-images.githubusercontent.com/15166619/228122854-e8624976-2ecd-4446-a686-4e25647d2350.png)
After successful writing, the node state will be updated to the correct form.

**Logs and Packet Captures**
Here is a snippet of my test program:
```
@Test
public void writeMatrixValue() throws Exception {
    OpcUaClient client = getOpcUaClient("opc.tcp://WIN-J3CRL509SHS:48010");
    NodeId nodeId = new NodeId(2, "Demo.Static.Matrix.Byte");
    DataValue dataValue = new DataValue(new Variant(
            new UByte[][]{
                    new UByte[]{UByte.valueOf(11)}
            }
    ), StatusCode.GOOD, null);
    StatusCode statusCode = client.writeValue(nodeId, dataValue).get();
    log.debug("{}", statusCode);
}
```
If you write a two-dimensional array just like in the program, it can be successful.
![78093ebcd599c6fdf4ed27659a7cc95](https://user-images.githubusercontent.com/15166619/228123322-719637f8-ab21-4ab4-81de-7e16dd119c59.png)

But if you change the value to be written to a one-dimensional array, you will get the error mentioned before. like this:
```
DataValue dataValue = new DataValue(new Variant(
        //new UByte[][]{
                new UByte[]{UByte.valueOf(11)}
        //}
), StatusCode.GOOD, null);
```

**Additional context**
The tested server program is UaCPPServer from Unified Automation.
The milo library used is the latest version 0.6.8.

**Comment by kevinherron** [comment]
Do you have Wireshark captures that can be compared? That seems like the easiest approach to figure out what is different.

**Comment by kdai319** [comment]
Okay, buddy.
These are wireshark packages for your reference.
[pcapng.zip](https://github.com/eclipse/milo/files/11091278/pcapng.zip)

**Comment by kevinherron** [comment]
I don't know if this can be matched right now. Explicit Matrix support has been added in the `dev/1.0` branch but there isn't an exact equivalent in the current releases. 

Right now it looks like you would have to pass in what you already tried (2 or more dimensional array) in order for the array dimensions to be included and indicated in the encoding mask [0].

Milo:
![image](https://user-images.githubusercontent.com/340273/228294577-82428ac6-7138-4cb4-851d-75a3a99544e5.png)

UaExpert:
![image](https://user-images.githubusercontent.com/340273/228294708-05c7a6bc-f64c-4fe6-b9c6-feda458572f6.png)


[0] https://reference.opcfoundation.org/Core/Part6/v105/docs/5.2.2.16

**Comment by kevinherron** [comment]
I am also not convinced the server should even accept the write from UaExpert because now the Array Dimensions do not match the value.
