### ISSUE TITLE
Get associated username from a ServiceRequest object

### ISSUE THREAD

**Issue by magnus-lutz** [eclipse/milo#111]
I have been missing the possibility to get the associated username withing a request listener, so that I can handle a Read/Write/Browse request depending on the requesting user/client.

**Comment by kevinherron** [comment]
`Session#getIdentityObject` should give you the object your `IdentityValidator` returned after validating a user, which is just a String with the username in the default implementation.

**Comment by kevinherron** [comment]
If you've got any further questions feel free to join the gitter channel and ask 👍
