### ISSUE TITLE
Dependency puppycrawl.checkstyle is vulnerable in version 8.18

### ISSUE THREAD

**Issue by GoetzGoerisch** [eclipse/milo#1121]
**Describe the bug**
The dependency:
https://github.com/eclipse/milo/blob/18b716c0f87b8431a5ab9ae734ecf6d1d0e71338/pom.xml#L214-L216
Contains a sec vulnerability described in https://github.com/checkstyle/checkstyle/security/advisories/GHSA-763g-fqq7-48wg

**Comment by kevinherron** [comment]
Checkstyle is eventually going to get upgraded for the 1.0 release. Right now when I upgrade it seems new rules cause failures.

There's no immediate danger here. From the link:

> Impact
> User: Build Maintainers
> 
> This vulnerability probably doesn't impact Maven/Gradle users as, in most cases, these builds are processing files that are trusted, or pre-vetted by a pull request reviewer before being run on internal CI infrastructure.
