### ISSUE TITLE
Update Bouncy Castle Dependencies in milo:stack-core

### ISSUE THREAD

**Issue by PierreLecomte7** [eclipse/milo#1133]
Hi, I noticed that milo:stack-core is using the Bouncy Castle library: bcprov-jdk15on, which is no longer maintained. The package that should be used is bcprov-jdk18on as Milo requires at least JDK8

Currently, a security vulnerability has emerged in the bcprov-jdk15on package, and it cannot be fixed.

Can you change the dependency used by milo:stack-core to bcprov-jdk18on ? Additionally, the bcpkix-jdk15on package should also be changed to bcpkix-jdk18on.

**Comment by kevinherron** [comment]
I can do this in the next release.
