### ISSUE TITLE
Are we able to get data point configs values?

### ISSUE THREAD

**Issue by yond13** [eclipse/milo#116]
Hey, i'm trying to get value from data point config, e.g. 'data.point:_online.._user' (SIMATIC WinCC OA).
I'm getting DataValue with Status = "Uncertain_InitialValue" and value = "false" (it supposed to return Integer value). 
Do you have any ideas whether we can get data point config value using Milo?

**Comment by kevinherron** [comment]
I'm not sure what you're asking exactly as it sounds very specific to the
server you're connected to, but if you shared some code you're working with
I might be able to help more.

It sounds like the read you're doing is working, so maybe you're pointing
at the wrong node or maybe the datatype isn't what you're expecting it to
be.
