### ISSUE TITLE
package not found [org.opcfoundation.opcua.binaryschema]

### ISSUE THREAD

**Issue by NotFeel** [eclipse/milo#1190]
import org.opcfoundation.opcua.binaryschema.FieldType;
import org.opcfoundation.opcua.binaryschema.StructuredType;
import org.opcfoundation.opcua.binaryschema.SwitchOperand;

Hello, may I ask if the above classes cannot be imported, how can I find them?

**Comment by kevinherron** [comment]
These classes get code generated in the `bsd-core` project when you build.

**Comment by NotFeel** [comment]
Thank you for your answer, your answer helped me!😀
