### ISSUE TITLE
cant't write a Long value to opc-ua(the data type is UInt32)

### ISSUE THREAD

**Issue by anganing** [eclipse/milo#1198]
**Describe the bug**
UInt32 the data type of opc-ua --> java's data type Long
is that ?

**Expected behavior**
A clear and concise description of what you expected to happen instead.

**Logs and Packet Captures**
![image](https://github.com/eclipse/milo/assets/63218247/1a6919da-6782-4805-a187-11ecc18e213d)
![image](https://github.com/eclipse/milo/assets/63218247/0bf85c0f-5689-4e6b-9eb1-48be33e3fb5e)

**Additional context**
Milo:v0.6.3 OPC-UA server :simess s7-1500

**Comment by kevinherron** [comment]
I'm guessing you figured this out, but if anybody else stumbles on this post, there are unsigned types in the `org.eclipse.milo.opcua.stack.core.types.builtin.unsigned` package:
- `UByte`
- `UShort`
- `UInteger`
- `ULong`
