### ISSUE TITLE
How to read CustomStructType?

### ISSUE THREAD

**Issue by anganing** [eclipse/milo#1207]
hello, I do it with your demo!

this is my code:
![image](https://github.com/eclipse/milo/assets/63218247/2383c631-9033-4a54-b1e6-48b134568d2f)
![image](https://github.com/eclipse/milo/assets/63218247/8a4418fb-4f97-4ad8-a125-1b10658afb15)
![image](https://github.com/eclipse/milo/assets/63218247/d4641812-78d3-4923-99e4-8b6ae97b8e4e)
![image](https://github.com/eclipse/milo/assets/63218247/289cb5df-e2ab-45a9-997c-85ecc87fdb7b)
 
how to fill the params make it work?

**Comment by kevinherron** [comment]
Before the error, print out all the namespace URIs that are in `client.getNamespaceTable()`.
