### ISSUE TITLE
How to get a Node from NodeId ?

### ISSUE THREAD

**Issue by AndreGuerra123** [eclipse/milo#125]
For instance I know its possible to retrieve nodeID from Node but it I didn't find the parse back to Node.
The only method I found similar to what I need is :  client.getAddressSpace().getNodeInstance(NodeId) but gives me a UaNode not a Node class. Which should I be working with since I'm building a simplistic client interface? Regards, André

**Comment by kevinherron** [comment]
`UaNode` implements the `Node` interface, so you can use either type.

Please use the mailing list or gitter.im for general questions and save the GH issue tracker for bug reports.
