### ISSUE TITLE
OPC-SDK-Server does not import with MAVEN into eclipse.

### ISSUE THREAD

**Issue by Muddasir-Shakil** [eclipse/milo#127]
Dear Sir
I am trying to learn more about eclipse milo. I am just starting with it problem that I am facing is when i import milo project in to eclipse with MAVEN I get all other packages just fine like SDK CLIENT, CORE and STACK but I can not import OPC UA SERVER and thus I can not build any example since it is being used in every example. 
I have attached the screen shots, it includes ExampleServer as well. 

![2017-07-24 13_20_09-eclipse-milo-project - server-examples_src_main_java_org_eclipse_milo_examples_s](https://user-images.githubusercontent.com/30407857/28521222-e4bce99e-7072-11e7-9248-0d1868bee9b7.png)
![2017-07-24 13_19_25-eclipse-milo-project - server-examples_src_main_java_org_eclipse_milo_examples_s](https://user-images.githubusercontent.com/30407857/28521221-e4bc52d6-7072-11e7-9491-7abb26f9c9f2.png)

**Comment by ctron** [comment]
As there are many ways to import things into Eclipse, could you please describe how you did it?

The last time I did that a few days ago, using "Import …" → "Maven / Import Existing Projects", it worked fine.

**Comment by Muddasir-Shakil** [comment]
I did the same way in to ecplipse using import-> Maven->Import Existing Pojects, It is working fine for OPC UA SDK Client Core and Stack but as you can see in the second snapshot I am missing OPC UA SDK server, there is nothing in the folder.

**Comment by ctron** [comment]
This is how it looks for me:
![image](https://user-images.githubusercontent.com/202474/28521937-369321ea-7076-11e7-9470-348e3bf3c083.png)

**Comment by Muddasir-Shakil** [comment]
this is how mine looks like :(
![image](https://user-images.githubusercontent.com/30407857/28522017-8cf2bb7c-7076-11e7-8688-d55160fa38da.png)

**Comment by ctron** [comment]
So maybe you deleted some part of the code by accident. It is in the repository: https://github.com/eclipse/milo/tree/master/opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server

So I would suggest to do a fresh checkout.

**Comment by Muddasir-Shakil** [comment]
I just checked my local repository and this folder exsits there along with all the files from where i am creating Maven project also other file like client and Core exists too but I have problem only with it I have downloaded it twice and build the project but i got sam errors. OPC ua SDK Server still mising.

**Comment by Muddasir-Shakil** [comment]
Ok I do not know the roots of the problem but i that much i know that i was using Eclipse Oxygen but when I created Maven project with Neon it works fine.
