### ISSUE TITLE
New Custom Data Types In OPC UA Clients. 

### ISSUE THREAD

**Issue by Muddasir-Shakil** [eclipse/milo#128]
Dear Sir
I have a server with Open62541 and Client with eclipse milo. I am trying to work with Custom data types, structs in c++. 
In Open62541 we can add CustomDataTypes in Server and Client confugration and the "en" and decoding is performed there automatically. 
I am stuck with eclipse Milo how do decode such Datatype in milo client. 
I have created the custom datatype class but I do not know how to give the data type description in milo client. 
Could you help me out here. 
thank you.

**Comment by kevinherron** [comment]
This is possible in the upcoming 0.2.0 release but I don't think it can be
done on the 0.1.x series.
