### ISSUE TITLE
Milo async subscription

### ISSUE THREAD

**Issue by spyff** [eclipse/milo#129]
Hello!

It is possible to subscribe for a variable change without busy polling? I mean, there is `MonitoringParameters` and I can specify `_samplingInterval` for 10 millisec, but I would like to know if there is a way to make a callback, which is fires on data changes. Thanks!

**Comment by kevinherron** [comment]
The Sampling Interval for a MonitoredItem is used to indicate the rate at which the server samples the underlying data. The Publishing Interval of the subscription defines the rate at which the subscription "executes" and sends any data changes that have accumulated back to the client.

The way subscriptions work is defined by the UA specification. True unsolicited data changes on a per-item basis is not possible.

**Comment by spyff** [comment]
Thank You for the clarificaion, I keep these in mind.
