### ISSUE TITLE
The client incorrectly verifies the sequenceNumber and triggers inactive.

### ISSUE THREAD

**Issue by greenpupil** [eclipse/milo#1346]
**Describe the bug**
SecurityPolicies with LegacySequenceNumbers set to FALSE，the SequenceNumber shall start at 0 and not wrap aroud until it is equal to 4294967295(UInt30.MaxValue).Under these conditions, the client verify the SequenceNumber valid and trigger the client's session reActive.

**Expected behavior**
While the SequenceNumber  start at 0 after it is equal to 4294967295(UInt30.MaxValue), the client should not transfer to inActive and then transfer Active.

**Logs and Packet Captures**
[TRACEID:][2024-11-04 08:29:02,063837600][10684][milo-shared-thread-pool-86217][ERROR][?.()/] - Error decoding symmetric message
org.eclipse.milo.opcua.stack.core.channel.MessageDecodeException: UaException: status=Bad_SecurityChecksFailed, message=expected sequence number 4294967296 but received 0
	at org.eclipse.milo.opcua.stack.core.channel.ChunkDecoder.decode(ChunkDecoder.java:97) ~[stack-core-0.6.11.jar!/:0.6.11]
	at org.eclipse.milo.opcua.stack.core.channel.ChunkDecoder.decodeSymmetric(ChunkDecoder.java:77) ~[stack-core-0.6.11.jar!/:0.6.11]
	at org.eclipse.milo.opcua.stack.client.transport.uasc.UascClientMessageHandler.lambda$onSecureMessage$14(UascClientMessageHandler.java:623) ~[stack-client-0.6.11.jar!/:0.6.11]
	at org.eclipse.milo.opcua.stack.core.channel.SerializationQueue.lambda$decode$1(SerializationQueue.java:63) ~[stack-core-0.6.11.jar!/:0.6.11]
	at org.eclipse.milo.opcua.stack.core.util.TaskQueue$TaskWrapper.run(TaskQueue.java:273) ~[stack-core-0.6.11.jar!/:0.6.11]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.eclipse.milo.opcua.stack.core.UaException: expected sequence number 4294967296 but received 0
	at org.eclipse.milo.opcua.stack.core.channel.ChunkDecoder$AbstractDecoder.decode(ChunkDecoder.java:203) ~[stack-core-0.6.11.jar!/:0.6.11]
	at org.eclipse.milo.opcua.stack.core.channel.ChunkDecoder.decode(ChunkDecoder.java:89) ~[stack-core-0.6.11.jar!/:0.6.11]
	... 7 more

**Additional context**
Version of Eclipse Milo you are using, OPC UA client or software server you are interacting with, etc...
This problem happen with version 0.6.11.
![image](https://github.com/user-attachments/assets/ba05d3d9-6ea5-4429-af27-caabd2520b7f)
This problem is not fixed.

**Comment by kevinherron** [comment]
All RSA-based security policies are defined with `LegacySequenceNumbers=TRUE`, i.e. all policies supported by this library.

Therefore the expected behavior is:
>[SecurityPolicies ](https://reference.opcfoundation.org/search/359?t=SecurityPolicies)with [LegacySequenceNumbers](https://reference.opcfoundation.org/search/359?t=LegacySequenceNumbers) set to TRUE, the SequenceNumber shall monotonically increase for all Messages and shall not wrap around until it is greater than 4 294 966 271 (UInt32.MaxValue – 1 024). The first number after the wrap around shall be less than 1 024.

Which seems to match the behavior of `LegacySequenceNumberValidator` to me.

**Comment by cityWalker312** [comment]
> All RSA-based security policies are defined with `LegacySequenceNumbers=TRUE`, i.e. all policies supported by this library.
> 
> Therefore the expected behavior is:
> 
> > [SecurityPolicies ](https://reference.opcfoundation.org/search/359?t=SecurityPolicies)with [LegacySequenceNumbers](https://reference.opcfoundation.org/search/359?t=LegacySequenceNumbers) set to TRUE, the SequenceNumber shall monotonically increase for all Messages and shall not wrap around until it is greater than 4 294 966 271 (UInt32.MaxValue – 1 024). **_The first number after the wrap around shall be less than 1 024_**.
> 
> Which seems to match the behavior of `LegacySequenceNumberValidator` to me.

It is also protocol compliant if the first SequenceNumber is assigned as 0 when the current SequenceNumber is flipped. However, our current implementation causes this problem.
![image](https://github.com/user-attachments/assets/9f17ed9f-814a-43a3-a8f0-4c78ba0df116)

**Comment by cityWalker312** [comment]
> All RSA-based security policies are defined with `LegacySequenceNumbers=TRUE`, i.e. all policies supported by this library.
> 
> Therefore the expected behavior is:
> 
> > [SecurityPolicies ](https://reference.opcfoundation.org/search/359?t=SecurityPolicies)with [LegacySequenceNumbers](https://reference.opcfoundation.org/search/359?t=LegacySequenceNumbers) set to TRUE, the SequenceNumber shall monotonically increase for all Messages and shall not wrap around until it is greater than 4 294 966 271 (UInt32.MaxValue – 1 024). The first number after the wrap around shall be less than 1 024.
> 
> Which seems to match the behavior of `LegacySequenceNumberValidator` to me.

https://reference.opcfoundation.org/Core/Part6/v105/docs/6.7.2.4

**Comment by kevinherron** [comment]
@cityWalker312 you're right, as the spec reads I think that line should be `sequenceNumber >= 0 && sequenceNumber < 1024`.

I'm asking some other OPCF members where I might have got this idea that sequence should rollover to 1. I suspect some old version of the spec suggested clients roll over to 1 but servers accept 0 or 1, or something along those lines. We'll see.
