### ISSUE TITLE
DateTime should provide conversion to Instant

### ISSUE THREAD

**Issue by ctron** [eclipse/milo#138]
`DateTime` currently provides a conversion to Java `Date`. But it does not provide a conversion to `Instant`, which would also support nano-seconds, which `Date` does not.

**Comment by kevinherron** [comment]
I have not used this new API but it seems reasonable.

The implementation will have to be smarter than just `getJavaDate().toInstant()` in order to preserve any nanosecond precision there might be.

**Comment by ctron** [comment]
> The implementation will have to be smarter than just getJavaDate().toInstant() in order to preserve any nanosecond precision there might be.

That is why I raised this issue instead of a PR 😁

**Comment by point85** [comment]
If millisecond precision for an application is "good enough", these two methods will be useful:

	// create a UTC ZonedDateTime from the DateTime
	public static ZonedDateTime utcTimeFromDateTime(DateTime dateTime) {
		long epochMilli = dateTime.getJavaTime();
		Instant instant = Instant.ofEpochMilli(epochMilli);
		ZonedDateTime time = ZonedDateTime.ofInstant(instant, ZoneId.of("Z"));
		return time;
	}
	
	// create a local ZonedDateTime from the DateTime
	public static ZonedDateTime localTimeFromDateTime(DateTime dateTime) {
		ZonedDateTime utc = utcTimeFromDateTime(dateTime);
		ZonedDateTime time = utc.withZoneSameInstant(ZoneId.systemDefault());
		return time;
	}
