### ISSUE TITLE
About returnDiagnostics & HistoryRead

### ISSUE THREAD

**Issue by ChaJiWon** [eclipse/milo#140]
Hi, I have questions of UA-milo library.
I'm doing CTT using application based UA-milo lib.

Some CTT(attribute service read) cases need setting of returnDiagnostic parameter.
In  OpcUAClient class, it doesn't have API setting returnDiagnostic in newRequestHeader. returnDiagnostic is fixed of uint(0). 
Is it intended? Or not, Do you have a plan supporting that in 1.04 release?

I'm wondering 1 more thing.  

I saw historyRead(.. ) API in AttributeHistoryManager class. I think that API make Bad_NotSupported status code when client call histroyread().

Isn't HistoryRead & HistoryUpdate feature supported in UA-milo?

**Comment by kevinherron** [comment]
Support for requesting and providing return diagnostics is not well supported in either the client or server right now. I'm hoping to change this in a later release.

As for HistoryRead and HistoryUpdate, it depends on what you mean by "supported". It's possible for your Namespace to implement those services but the SDK does not provide implementations for you.
