### ISSUE TITLE
Add a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by ctron** [eclipse/milo#144]
I think it is necessary to add a file about contributing to Milo, also see #143 

Most Eclipse projects have this and I think the one from Eclipse Hono [1] could act as a base for Milo as well.

@kevinherron If you like I can create such a file for Milo

[1] https://github.com/eclipse/hono/blob/master/CONTRIBUTING.md

**Comment by kevinherron** [comment]
Yes, please do. I was going to add one when I updated the license files for EPL 2.0, but there's no reason to wait.

**Comment by ctron** [comment]
I created a PR, because I think you should double check.
