### ISSUE TITLE
Roadmap 

### ISSUE THREAD

**Issue by lln-ijinus** [eclipse/milo#146]
Would it be possible to have a roadmap about the project ?

Not something to big, just to know which parts of the server / client /stack are done, what big features need to be done, and what's in the next version (and possibly an aproximative due date)

For example, I'm searching for historical events in the server, but I don't know if I it's implemented ?
Also, I would like to help but don't know what is needed (some directed bug fix issues could be nice, too)

Anyway, thanks a lot for the project !

**Comment by kevinherron** [comment]
Yes, excellent idea.

**Comment by jamesmarkchan** [comment]
Yeah a roadmap could really help organize contributions and clarify
priorities. A bulleted list under release version targets has pretty low
overhead.

**Comment by kevinherron** [comment]
So I still don't have a traditional roadmap, but... as you can see by the state of the issues and PRs I'm trying to dump the TODO list from my head into GitHub in order to provide a little more transparency about what's happening now and what's on its way.
