### ISSUE TITLE
Class cast Exception SOS

### ISSUE THREAD

**Issue by royalcrownlei** [eclipse/milo#148]
When I excute the following code ;
ServerStatusNode serverStatusNode = serverNode.serverStatus().get();
I get the exception :java.lang.ClassCastException: Cannot cast org.eclipse.milo.opcua.sdk.client.nodes.UaVariableNode to org.eclipse.milo.opcua.sdk.client.model.nodes.variables.ServerStatusNode;
can you help me  thank you!

**Comment by royalcrownlei** [comment]
the  server is  my own, not the milo example

**Comment by royalcrownlei** [comment]
but the server  is normal   I can accept message from it

**Comment by kevinherron** [comment]
Sounds like the same issue as #147

**Comment by kevinherron** [comment]
See #147 for problem and work-around.

**Comment by royalcrownlei** [comment]
thanks   it is OK now !!!
