### ISSUE TITLE
Add EUInformation from Unece CeFact

### ISSUE THREAD

**Issue by lln-ijinus** [eclipse/milo#150]
It could be nice to have a list of EUInformation from the Unece CeFact,  as defined in Spec. 1.03 Part 8, like in other OPC UA SDK.

I've made a simple one file parser of the https://opcfoundation.org/UA/EngineeringUnits/UNECE/UNECE_to_OPCUA.csv file but don't really find where to include it in the source tree for a pull request.
[CefactEUInformationsParser.java.txt](https://github.com/eclipse/milo/files/1454700/CefactEUInformationsParser.java.txt)
[CefactEngineeringUnits.java.txt](https://github.com/eclipse/milo/files/1454706/CefactEngineeringUnits.java.txt)

**Comment by kevinherron** [comment]
I think in `sdk-core` under the `org.eclipse.milo.opcua.sdk.core` package.

Don't commit the CSV and Parser; just `CefactEngineeringUnits` class. Submit it as a PR and leave the "edits from maintainers" checkbox enabled and I'll help you tweak it a bit.
