### ISSUE TITLE
The older Version 

### ISSUE THREAD

**Issue by OrangeAlex** [eclipse/milo#178]
hi，
    where could  i  get the milo version 1.0.0

**Comment by kevinherron** [comment]
There is no version 1.0.0. Do you mean 0.1.0?

**Comment by OrangeAlex** [comment]
Yes  i mean 0.1.0

**Comment by kevinherron** [comment]
You can checkout the "v0.1.0" tag and build it yourself or get the artifacts from [Maven Central](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.eclipse.milo%22%20AND%20a%3A%22milo%22).
