### ISSUE TITLE
How Multiple clients receive message from opc server by publish-subscribe mode

### ISSUE THREAD

**Issue by zweifang** [eclipse/milo#180]
Hi~   I have a ploblem when I use publish-subscribe mode to receive message from opc server. I have some java clients,which register the same key on the opc server.So when the key's value change,all of the clients will receive the same message.How can I receive the message  by only one client ,not all the clients?

**Comment by zweifang** [comment]
Sorry I make a mistake, It is Subscription model

**Comment by kevinherron** [comment]
That's how subscriptions work, it can't be avoided. 

Perhaps you're trying to use OPC UA or subscriptions for something they aren't meant for?
