### ISSUE TITLE
Let the SubscriptionListener provide empty default methods

### ISSUE THREAD

**Issue by ctron** [eclipse/milo#19]
I think it would be nice to either have the `SubscriptionListener` provide empty default methods or to have a `DefaultSubscriptionListener` which implements the interface with empty methods.

This makes is easier when you only need one method to be called.

**Comment by ctron** [comment]
If you like I can make the change and do a PR.

**Comment by kevinherron** [comment]
Yes, go ahead and add empty defaults to `SubscriptionListener`.

`onStatusChanged` and `onSubscriptionTransferFailed` should not be ignored though; maybe we could not add default implementations for these?

**Comment by ctron** [comment]
Sorry for the delay. But here it is.
