### ISSUE TITLE
Using enum for Method Arguments

### ISSUE THREAD

**Issue by hakjac** [eclipse/milo#199]
Hi!

I'm implementing a OpcServer and like to use enums for some method arguments. I cannot find any example of this. I have successfully implemented methods with arguments of other types, such as UShort, Double etc. Can you give me some input or an example on how to use enums instead?

**Comment by kevinherron** [comment]
Is this for an enum you want to define (another question in its own, only recently possible) or for an existing enum?

**Comment by hakjac** [comment]
Hi Kevin! I want to define my own enums and use for input/output method arguments. I'm currently using numbers according to style in the SqrtMethod example.

E.g I want to accomplish something like this:

Enum: TempSensor (WaterTempSensor=0, AirTempSensor=1)
Enum ReturnCode (OK=0, NotOK=1)

Method: GetTemperature with
InputArgument: sensor, type:Sensor
OutputArgument: temperature, type Double
OutputArgument: returnCode, type: ReturnCode

Best Regards / Håkan

**Comment by CB-IT** [comment]
Hi Håkan,
could you solve your problem? At the moment I'm facing a similar issue:
[https://stackoverflow.com/q/53490969](url)
Thanks in advance

**Comment by kevinherron** [comment]
#415 introduces `AbstractMethodInvocationHandler` which should easily support enum argument types.
