### ISSUE TITLE
Wiki Update

### ISSUE THREAD

**Issue by amitjoy** [eclipse/milo#20]
It would be really helpful if you can update wiki on how to use the library. I would also suggest you to add your example application to this repo as well. It would definitely be helpful to other developers.

**Comment by kevinherron** [comment]
That's part of the plan! :smile:

**Comment by jpposteuca** [comment]
Is there any other place to get documentation on how to use the library?  I've started working with the sample OPC server, but I'm not sure what all the code does.  For instance, the SubscriptionModel is a bit mysterious.  Thanks in advance!

**Comment by kevinherron** [comment]
@jpposteuca documentation is still largely a TODO, unfortunately.

As for `SubscriptionModel`... that's just a naive implementation of the methods needed to implement `MonitoredItemManager` so the example server can handle subscriptions. What makes it especially naive is it just delegates out to the read service calls. In the "real world" you would ideally have some way of actually subscribing to this data.
