### ISSUE TITLE
Some question about Modbus Transfer to OPC UA

### ISSUE THREAD

**Issue by OrangeAlex** [eclipse/milo#218]
hi , kevin
     As i know, the project Milo implement OPC UA protocol , i have a question that , if I have some device based on the ModBus,  i want use milo to access these devices, do you have some plan to implement this feature : a component that can transfer the ModBus to OPC UA , or  this feature has been exist in the milo?
     i am looking forward your response 
     thank you

**Comment by kevinherron** [comment]
No, that would be a feature that an OPC UA server application would provide. Milo is only an SDK for building such an application.
