### ISSUE TITLE
Eternal loop waiting for operation completion

### ISSUE THREAD

**Issue by miroch41** [eclipse/milo#242]
Some client's operations are implemented based on events fired by _org.eclipse.milo.opcua.sdk.client.session.SessionFsm.fireEvent()_. An example of such operation is _OpcUaClient.disconnect().get()_. However, _fireEvent_ delegates the execution to the session's state and if the current state does not recognize the event in question, it performs no operation. In the specific case of _OpcUaClient.disconnect().get()_: if a client with session's state _Inactive_ (that is, a not-connected client) tries to disconnect, nothing happens and the controlling thread hangs waiting for completion of a future which never completes.

It may sound as a silly scenario (to disconnect a not-connected client) but it is a natural behavior when recovering a seriously failed client: the actual client's state need not be known in this case and one just tries to disconnect the client to release all its resources - it may happen that the client is already disconnected (or has never really been connected).

I am not sure how the client should react in this case, but it should react somehow instead of waiting eternally. For example it could:

- throw an exception (meaning "you cannot disconnect a not-connected client")
- return successfully (meaning "a client is not-connected, that is, this is a no-op request")

Note that this problem need not be bound to the disconnect-operation and state _Inactive_ only: similar problems may exist for other client's operations and other session's states.

**Comment by kevinherron** [comment]
I'll look into this. It's possible this exists in other states, but it *is* something I did try to account for. 

It looks like I missed this scenario in the Inactive state though.
