### ISSUE TITLE
Resources not released completely

### ISSUE THREAD

**Issue by miroch41** [eclipse/milo#243]
I tried the following scenario:

- Server gets started
- External client running in different Java VM connects to the server
- Server has been shut down (without disconnecting the external client)
- Cleanup of resources on server using _org.eclipse.milo.opcua.stack.core.Stack.releaseSharedResources_

Now, _releaseSharedResources_ performs graceful release - within timeout passed as a method parameter. However, only by really large timeout all threads get terminated. The problem is in a **ua-shared-scheduled-executor-*** thread created for _Stack.SCHEDULED_EXECUTOR_SERVICE_. Being initialized by _Executors.newSingleThreadScheduledExecutor_, the created thread is a default _ScheduledThreadPoolExecutor_ instance whose policy for _executeExistingDelayedTasksAfterShutdown_ is by default set to true (see _java.util.concurrent.ScheduledThreadPoolExecutor.executeExistingDelayedTasksAfterShutdown_) 

As a result, this thread does not terminate even after calling _ExecutorService.shutdown_ and _awaitTermination_ (unless the timeout is relatively large) if there is a long-lasting delayed task submitted before _ExecutorService.shutdown_ has been initiated. And indeed, there is (at least one) such task: the one created by a constructor of _org.eclipse.milo.opcua.sdk.server.Session_ for session timeout (2 minutes by default). Therefore, the resources cannot be completely released before timeout for all sessions expires, although the server has already been shut down.

**Comment by kevinherron** [comment]
Thank you for the detailed analysis 👍
