### ISSUE TITLE
What is the port address of server-examples?

### ISSUE THREAD

**Issue by BIT-masterpy** [eclipse/milo#259]
Hi, I use a third-party client to connect server-examples to fail.What should I do with it?

![2018-04-16_141333](https://user-images.githubusercontent.com/30205233/38792912-b8fd114a-4181-11e8-82e4-46c950a20d38.png)

![2018-04-16_141421](https://user-images.githubusercontent.com/30205233/38792949-db87b878-4181-11e8-94ee-3267b6df5ce5.png)

**Comment by jiangxingang** [comment]
12686
