### ISSUE TITLE
can't find class in org.eclipse.milo.opcua.binaryschema.GenericBsdParser.java

### ISSUE THREAD

**Issue by MeowStone** [eclipse/milo#263]
```
import org.eclipse.milo.opcua.binaryschema.parser.BsdParser;
import org.eclipse.milo.opcua.stack.core.serialization.codecs.OpcUaBinaryDataTypeCodec;
import org.opcfoundation.opcua.binaryschema.EnumeratedType;
import org.opcfoundation.opcua.binaryschema.StructuredType;

public class GenericBsdParser extends BsdParser {
 somecode.....
}
```
lack of class EnumeratedType and StructuredType

**Comment by kevinherron** [comment]
Have you run `mvn install` from the base directory using JDK 8? These classes need to be generated.

**Comment by kevinherron** [comment]
Alternatively, you can convince whatever IDE you use to run the `jaxb2:xjc` Maven plugin/goal.

**Comment by kevinherron** [comment]
How does it fail? What's the error?

**Comment by kevinherron** [comment]
Closing this. If you need further help on this topic use the mailing list.
