### ISSUE TITLE
NODE TYPE

### ISSUE THREAD

**Issue by manijndl** [eclipse/milo#273]
is there any method to get all the nodes which are of type Object only??

**Comment by manijndl** [comment]
client.getAddressSpace().browse(browseRoot).get() this method returns nodes in which order lexographical order or dependent on some other parameter?

**Comment by kevinherron** [comment]
The order is up to the server, there's no requirement or expectation.

You can filter a browse to only return Object nodes using the `nodeClassMask` field of `BrowseDescription`, but you can't just as for all Object nodes in the entire server.
