### ISSUE TITLE
can not write to a node

### ISSUE THREAD

**Issue by hbbend** [eclipse/milo#286]
Hi Kevin,
My problem is, when i connect to a PLC OPC UA server I can browse, but i can not read nor write. (bad nod Id Unknown, this node does not exist in the servers address space).
""...it works successfully with other servers..."".

I solved the problem of reading by browsing to the node then read it. (see #285 )
however when i try the same thing with writing, I do not get any exception, but it the value attribute does not change, it simply don't write.
would you help me with this, thank you
B/R

**Comment by kevinherron** [comment]
You're not waiting for the write to finish in your example. All calls are async.

Try this instead: `client.writeValue(NodeId1, VV).get();`

**Comment by hbbend** [comment]
same result, node value still the same.

please find below the code 


	private Object HbrowseWrite(OpcUaClient client, NodeId browseRoot, NodeId NodeIdVariable) {
		
		Object ValeurLue = null;
		Object resultat = null;
	    int v = 22;
        Variant vv = new Variant(v);  
        DataValue VV = new DataValue(vv, null, null);
		
		try {
        	
            NodeId TestNodeId = null;
             
            VariableNode nodeVarLue = null;
            DataValue value1;
            
            List<Node> nodes = client.getAddressSpace().browse(browseRoot).get();

            for (Node node : nodes) {
            	TestNodeId = node.getNodeId().get();
            
            	 if (CompareNodeId(TestNodeId, NodeIdVariable))
            	 {
          		            	    
            		// new WriteValue(TestNodeId, uint(13), null, VV);   
    	     // client.writeValue(TestNodeId, VV);
    	      client.writeValue(TestNodeId, VV).get();
    	      nodeVarLue = client.getAddressSpace().createVariableNode(TestNodeId);   
   	      value1 = nodeVarLue.readValue().get();	
    	      ValeurLue = value1.getValue().getValue();            	    	            	               	    	            	       
    	      System.out.println("La nouvelle valeur de la variable : "+ NodeIdVariable.getIdentifier() + " est : "+ ValeurLue);           	    	            	                   	    	            	     
            	    
            	    
            	    break; 
            	 } 
                // recursively browse to children
                resultat = HbrowseWrite(client, node.getNodeId().get(), NodeIdVariable);
                if (resultat != null) {
                	ValeurLue = resultat;
                	break;
                }
                
            }
        } catch (InterruptedException | ExecutionException e) {
            logger.error("Browsing nodeId={} failed: {}", browseRoot, e.getMessage(), e);
        }
		
		return ValeurLue;
    }

I am using the browse with this server to read and write, because it does not find the node when simply read and write, as described above.
Thanks

**Comment by hbbend** [comment]
private boolean CompareNodeId(NodeId Node1, NodeId Node2){
		boolean result = false;
		if ((trimDoubleQuotes(Node1.getIdentifier().toString()).equals(Node2.getIdentifier().toString()) ) &
				(Node1.getNamespaceIndex().equals(Node1.getNamespaceIndex()))) result = true;
   	 {
   	 
   	 }
		
		return result;
		
	}
	
	public static String trimDoubleQuotes(String text) {
	    int textLength = text.length();

	    if (textLength >= 2 && text.charAt(0) == '"' && text.charAt(textLength - 1) == '"') {
	      return text.substring(1, textLength - 1);
	    }

	    return text;
	  }

**Comment by kevinherron** [comment]
Check the StatusCode returned by the server when you write. If it's Good, but the value doesn't change, the issue is not on the client side and you'll have to troubleshoot the server somehow.

**Comment by hbbend** [comment]
is there an instruction for that, or where to look?
thanks

**Comment by kevinherron** [comment]
When you call `client.writeValue(TestNodeId, VV).get()` the return value is a `StatusCode`...

**Comment by hbbend** [comment]
ah ok :))

**Comment by hbbend** [comment]
StatusCode{name=Bad_TypeMismatch, value=0x80740000, quality=bad}

**Comment by hbbend** [comment]
I tried with UInteger v = uint(22); same result

**Comment by hbbend** [comment]
![plc server displayed in uaexpert](https://user-images.githubusercontent.com/39961540/41295340-3e03e8d0-6e52-11e8-9a76-d57b8eba832a.PNG)

**Comment by kevinherron** [comment]
`Int16` is a Java `Short`, so make sure the value you're writing is cast to Short before you write it.

**Comment by hbbend** [comment]
it seems so simple dut, it does not acespt cast to Ushort, and  i don(t find how to import to Milo maven project a library who does that

**Comment by kevinherron** [comment]
I said `Short`, not `UShort`.

Something like: 
```java
Variant v = new Variant((short) 42);
DataValue dv = DataValue.valueOnly(v); 
```

**Comment by hbbend** [comment]
ok, i did it, but i got an exception:

`15:41:06.397 [main] ERROR org.eclipse.milo.Client.ClientRunner - Error running example: Variant cannot contain Variant
java.lang.IllegalArgumentException: Variant cannot contain Variant`

**Comment by hbbend** [comment]
sorry, one moment please

**Comment by hbbend** [comment]
ouf, its working !

**Comment by hbbend** [comment]
Thanks kevin, 
by the way, how can i run my project in another pc, because after i imported from existing maven projects, several projects are open in my workspace. And I want to pack them as before to use in another pc
