### ISSUE TITLE
Question: How to save and Export the Milo OPC UA Server to use it somewhere else

### ISSUE THREAD

**Issue by hbbend** [eclipse/milo#287]
After i imported from existing maven projects, several projects are open in my workspace. And I want to pack them as before to use in another pc. containing the JAVA project i want to use with Milo OPC UA Client.
First : How can i save and Export the Milo OPC UA Server/Client to use it somewhere else
Second: How to use it with existing projects already existing in that workspace

Thank's in Advance
B/R

**Comment by kevinherron** [comment]
Try asking the mailing list or gitter channel this question. It's not specific to Milo and I don't use Eclipse IDE or know how to answer it offhand.

You'd probably do well to search Google about creating a runnable JAR file.
