### ISSUE TITLE
Question: How to save and Export the Milo OPC UA Server to use it somewhere else

### ISSUE THREAD

**Issue by hbbend** [eclipse/milo#288]
#287 
I know how to create a runnable JAR file, for a java project,
however when importing Milo using Maven import, it is open in several projects.
by which one begin, and what to do?
I'll do the how :+1: 
it's for an important task
thanks in advance

![capture](https://user-images.githubusercontent.com/39961540/41301758-ba81c11c-6e60-11e8-8d84-4c77a5251064.PNG)

**Comment by kevinherron** [comment]
If you're building a client, the main project to depend on is `sdk-client`. For a server it's `sdk-server`. If you package/deploy it correctly the transitive dependencies should be included.

**Comment by hbbend** [comment]
it worked!
thanks a lot
