### ISSUE TITLE
How to connect to two and more opc servers with opc client.

### ISSUE THREAD

**Issue by magiino** [eclipse/milo#296]
Hello.
I have just one question.
If I understand correctly from examples, so if I want to be connected to two OPC servers at once, I have to create two OpcUaClient instances with different endpoint in configuration?

```java
UaTcpStackClientConfig config = UaTcpStackClientConfig.builder()
            .setApplicationName(LocalizedText.english("Stack Example Client"))
            .setApplicationUri(String.format("urn:example-client:%s", UUID.randomUUID()))
            .setCertificate(certificate)
            .setKeyPair(keyPair)
            .setEndpoint(endpoint)
            .build();
```
Thank you for clarification.
Marek

**Comment by kevinherron** [comment]
Yes, that's right. Each connection will have its own `OpcUaClient` instance.

**Comment by magiino** [comment]
Thanks!
