### ISSUE TITLE
Get all variable nodes / leaf nodes for a given URI (obtained from NamespaceTable) ?

### ISSUE THREAD

**Issue by dpnkr** [eclipse/milo#302]
Is there any way to get all the variable type nodes from a given namespace uri which I obtained from for example
`` client.getNamespaceTable().indexUriMap.tableLeft.get(1) ``  ?

**Comment by kevinherron** [comment]
There's no such method or service defined by OPC UA. You'll have to write some kind of browse routine that recursively browses and accumulates those nodes when it finds them.
