### ISSUE TITLE
Tag or nodes Synchronization

### ISSUE THREAD

**Issue by manijndl66** [eclipse/milo#314]
hi i want to synchronize all the opc tags is there support in eclipse milo for tag snchronization?

**Comment by kevinherron** [comment]
Do you mean reading or subscribing to tags to get their values? If so, yes.

**Comment by manijndl66** [comment]
no suppose one tag is added in the opc so to synchronize  that new tag information is there any event or support in milo?

**Comment by kevinherron** [comment]
The closest thing to this would be subscribing to events of type `GeneralModelChangeEventType`.

Event support in servers is optional and even they support events they don't necessarily support this one.

**Comment by kevinherron** [comment]
Also, I assume you're not just talking about browsing to discover what nodes exist initially.
