### ISSUE TITLE
EUROMAP import XML

### ISSUE THREAD

**Issue by AlthausOventrop** [eclipse/milo#315]
Hello!

I'm thinking about using the EUROMAP77 standard for connecting our plastics machinery.

Does anyone use this
 or is anyone able to give hints how to import the provided
 Opc_Ua.EUROMAP77.NodeSet2.xml
 to eclipse milo server ?

See here:
http://www.euromap.org/en/euromap77/

Any hint is welcome!

Greetings,
Stephan Althaus

**Comment by kevinherron** [comment]
While technically possible to parse and import this yourself, there's no official support for importing NodeSet XML files yet. It's one of the things I'm working on for the 0.3 release.
