### ISSUE TITLE
ERROR - Call error: Session Call error BadInternalError. 

### ISSUE THREAD

**Issue by MeowStone** [eclipse/milo#316]

**Comment by MeowStone** [comment]
can't use DataValue as a AnnotationBasedInvocationHandler.Out value?

**Comment by MeowStone** [comment]
error occured in AnnotationBasedInvocationHandler.java 
-----------------------------------------------------
 for(int i = 0; i < outputCount; ++i) {
        values[i] = new Variant(((AnnotationBasedInvocationHandler.OutImpl)outputs[i]).get());
}
-------------------------------------------------------
exception had been caught here

**Comment by MeowStone** [comment]
`checkArgument(!DataValue.class.equals(componentClazz), "Variant cannot contain DataValue");`
how can i return complicate data structure like DataValue?

**Comment by kevinherron** [comment]
From the spec:
>DataValue and DiagnosticInfo types only have meaning when returned in a response message
with an associated StatusCode. As a result, Variants cannot contain instances of DataValue or
DiagnosticInfo.

Use a different datatype here. You're misusing `DataValue`.

**Comment by kevinherron** [comment]
Well... for the results of method calls you can't.

**Comment by MeowStone** [comment]
@kevinherron thks to telling me this, multiple return/out parameters . but, i want to return parameters  like map

**Comment by MeowStone** [comment]
okay,so i can't return customtype data right now.
thks anyway :D

**Comment by kevinherron** [comment]
Ha, okay. `MethodInvocationHandler` doesn't have to be complicated - all it needs to do is validate the inputs received before invoking the logic.
