### ISSUE TITLE
Create CI job at HIPP instance

### ISSUE THREAD

**Issue by ctron** [eclipse/milo#32]
I do think it is time to create a Hudson (yes I know) job at your HIPP instance.

This would be a simple "Invoke Maven 3" job with `clean install deploy`. This would automatically push to the Nexus OSS repository, since you project is already set up for this.

If you like, I can help you setting this up, but you need to create the Hudson job.

**Comment by kartben** [comment]
FWIW you can also ask for a "JIPP" (i.e. Jenkins) instance. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=336262#c42

**Comment by ctron** [comment]
Cool, I didn't know they went "out of beta".

**Comment by kevinherron** [comment]
I've set up a job that runs `clean install deploy` but I'm still trying to figure out how to trigger it automatically.

**Comment by ctron** [comment]
Like that:

![hipp1](https://cloud.githubusercontent.com/assets/202474/17058487/fd850f9c-5020-11e6-87a1-8aa1c87a876a.png)

**Comment by ctron** [comment]
That is from the secondary package drone build: [1]

If you like I can assign you temporary access, so that you can peek.

[1] https://hudson.eclipse.org/package-drone/job/package-drone-secondary-build/

**Comment by kevinherron** [comment]
Okay... so it polls. Is it not possible to setup a webhook that triggers it?

**Comment by kevinherron** [comment]
Getting somewhere... it's failing to deploy because sonatype says unauthorized.

**Comment by kevinherron** [comment]
Got it working...

**Comment by ctron** [comment]
And you can have a nice shield too: ![Milo_Deploy](https://img.shields.io/jenkins/s/https/hudson.eclipse.org/milo/Milo_Deploy.svg)

**Comment by kevinherron** [comment]
I'll save that for when it's actually building successfully... there's some kind of bug that is happening when the tests run on the CI server, possibly related to the change that shut down and removed unused SocketServer instances.
