### ISSUE TITLE
Can't write to KepServer with boolean or word data types

### ISSUE THREAD

**Issue by Stranger87123** [eclipse/milo#324]
Hi:

I hope you can help me. I am trying to write to a node in KepServerEx 5 with Word DataType. 

https://www.dropbox.com/s/ek9eb5pks854agv/Sin%20t%C3%ADtulo.png?dl=0

The code looks like this:

client.writeValue (nodeId, new DataValue (new Variant ("word"), null, null, null));

The StatusCode looks like this:

StatusCode {name = Bad_TypeMismatch, value = 0x80740000, quality = bad}

Thank you very much.

**Comment by kevinherron** [comment]
The Word datatype in Kepware is probably either an Int16 or UInt16 in OPC UA, and you're trying to write the String value "word".
