### ISSUE TITLE
How to execute opc ua client ? 

### ISSUE THREAD

**Issue by ericccccccc** [eclipse/milo#330]
Thanks for your suggestions using  the  IDE to build the project.
Now i can execute the server,but i don't how to exeute the client in the eclipse IDE.
I have found there are  a lot of client example.
I want to execute the basic ExampleClient but there isn't have the main .
how to execute ?

thank you !!

**Comment by kevinherron** [comment]
There's no basic ExampleClient, just specific examples like `ReadExample` that *do* have a `main` you can start.

You don't need to start a server for these, they start one for you.

**Comment by ericccccccc** [comment]
thx~for your comment.
i have tried to start the ReadExample :
/client-examples$ mvn exec:java -D"exec.mainClass"="org.eclipse.milo.examples.client.ReadExample"

but i got the 2 error ~
![image](https://user-images.githubusercontent.com/35401606/46455735-e2690280-c7de-11e8-97ce-98572dd5b028.png)

![image](https://user-images.githubusercontent.com/35401606/46455749-f7459600-c7de-11e8-96f9-1e49c7252bdf.png)

and you say that "You don't need to start a server for these, they start one for you." , is that means i only need to start ReadExample then the ExampleServer will start too ?

I still got a lot problems, but thx for your help ^^

**Comment by kevinherron** [comment]
> and you say that "You don't need to start a server for these, they start one for you." , is that means i only need to start ReadExample then the ExampleServer will start too ?

Yes, that's why you get the BindException in your first screenshot.

**Comment by ericccccccc** [comment]
thx  a lot!!
