### ISSUE TITLE
Problems encountered in reading historical data 

### ISSUE THREAD

**Issue by tiedun001** [eclipse/milo#331]
The following problems were encountered when reading the historical data. 
[HistoryReadResult{StatusCode=StatusCode{name=Bad_NotSupported, value=0x803D0000, quality=bad}, ContinuationPoint=null, HistoryData=null}]
the point is bad_notsupported what's the problem?
please help me!

**Comment by kevinherron** [comment]
The server you're connecting to probably doesn't support historical services.

**Comment by kevinherron** [comment]
If you're using Milo SDK for the server, you've got quite a bit of work ahead of you. An implementation of historical services is not part of the SDK.

You can implement them yourself by overriding `AttributeHistoryServices#historyRead` and `AttributeHistoryServices#historyUpdate` in your `Namespace` implementation.

You'll need Part 4 and Part 11 of the OPC UA spec, at a minimum.

**Comment by tiedun001** [comment]
thank you.i  use Milo SDK for ua server.  I want to know the details of implementation.

**Comment by kevinherron** [comment]
The details of how to implement historical services are in Part 4 and Part 11 of the OPC UA specification.

I haven't implemented it myself so I can't provide any further help.

**Comment by tiedun001** [comment]
or other sdk has finished ?

**Comment by kevinherron** [comment]
> or other sdk has finished ?
I don't know.

There's no other open source Java SDK. One of the commercial SDKs may have history implemented for you to some degree.

**Comment by tiedun001** [comment]
thank you
