### ISSUE TITLE
Example for subscribing a node

### ISSUE THREAD

**Issue by Ox24** [eclipse/milo#36]
Can you please add an example to how to create a subscription on a node? Or maybe update your wiki in how to use the sdk..

Thx!

**Comment by kevinherron** [comment]
An example of how to do this is now provided: https://github.com/eclipse/milo/blob/master/milo-examples/client-examples/src/main/java/org/eclipse/milo/examples/client/SubscriptionExample.java

More examples will follow. Feel free to open a ticket if there is something in particular you need.
