### ISSUE TITLE
How to login OPC server with username and password

### ISSUE THREAD

**Issue by marttin-h** [eclipse/milo#371]
Hi,OPC Server run on PLC with the login password name. How do I connect to the server and load from the space "" ns = 6; s = :: AsGlobalPV: AWS.AWS_Bool "".

I use a username and password connection, return Exception:

> java.util.concurrent.ExecutionException: UaException: status=Bad_ConnectionRejected, message=java.net.ConnectException: Connection refused: no further information: br-automation/46.101.252.160:4840
> 	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
> 	at java.util.concurrent.CompletableFuture.get(Unknown Source)
> 	at OPCTest.main(OPCTest.java:76)
> Caused by: UaException: status=Bad_ConnectionRejected, message=java.net.ConnectException: Connection refused: no further information: br-automation/46.101.252.160:4840
> 	at org.eclipse.milo.opcua.stack.client.UaTcpStackClient.lambda$bootstrap$17(UaTcpStackClient.java:519)
> 	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:683)
> 	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:604)
> 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:564)
> 	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:425)
> 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:276)
> 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:292)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:545)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:485)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:399)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:371)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
> 	at java.lang.Thread.run(Unknown Source)
> Caused by: java.net.ConnectException: Connection refused: no further information: br-automation/46.101.252.160:4840
> 	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
> 	at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
> 	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:224)
> 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:289)
> 	... 6 more`

well thank you

**Comment by kevinherron** [comment]
You're getting a generic connection exception:

```
java.net.ConnectException: Connection refused: no further information: br-automation/46.101.252.160:4840
```

This means you haven't even gotten to the part where the username or password matters - you simply can't open a TCP connection to this server. Make sure you've got the right IP address and that there's actually a server running and accepting connections. Check your firewall. This is just a networking problem at this stage.
