### ISSUE TITLE
DepShield reports a vulnerabilty with netty in stack-core

### ISSUE THREAD

**Issue by point85** [eclipse/milo#373]
In my OEE project, I have DepShield scan my submissions for security vulnerabilities.  In my latest submission, DepShield flagged netty in the stack-core project.
![depshield vulnerability](https://user-images.githubusercontent.com/12372976/49264713-40435080-f404-11e8-9d3f-9bb5027b7221.PNG)

**Comment by kevinherron** [comment]
Milo doesn't use `OpenSslEngine` from Netty but I can upgrade to a later 4.0.x release anyway (for the 0.2 series).

The `dev/0.3` branch has already migrated to Netty 4.1.x.
