### ISSUE TITLE
Instantiation of ObjectType with layered components

### ISSUE THREAD

**Issue by Eichi87** [eclipse/milo#388]
As mentioned in the title, we try to instantiate an objecttype containing a component which contains another component.

The screenshots below show that this doesn't seem to work.

The Object:
![2](https://user-images.githubusercontent.com/7935497/50843106-5da2fd00-1368-11e9-958b-2b0c99c0a6dc.PNG)

The Node without the second component:
![1](https://user-images.githubusercontent.com/7935497/50843105-5da2fd00-1368-11e9-8415-75e118909159.PNG)

The code we use to instantiate the object is this:
```
this.uaObjectNode = new UaObjectNode[xmlImporter.getNumberOfTotalObjectTypes()];

        for(int i=0; i<this.uaObjectNode.length ; i++) {

           this.uaObjectNode[i] = nodeFactory.createObject(

                    new NodeId(2, "11000"),

                    new QualifiedName(2, this.xmlObjectType[i].getBrowseName()),

                    LocalizedText.english(this.xmlObjectType[i].getDisplayName()),

                    this.uaObjectTypeNode[i].getNodeId()

                );

           this.folderNode.addOrganizes(this.uaObjectNode[i]);
```

Should this work? Or does it work as intended?
Or are we missing something?

Thanks in advance
Daniel

**Comment by kevinherron** [comment]
Can you try this on the `dev/0.3` branch instead? NodeFactory was rewritten to fix these issues (hopefully).

**Comment by Eichi87** [comment]
The issue is resolved. Our mistake was, that we used types instead of components during the type definition.

**Comment by kevinherron** [comment]
Okay 👍
