### ISSUE TITLE
Error in ChannelConfig constructor maxChunkSize check?

### ISSUE THREAD

**Issue by extraneu** [eclipse/milo#395]
The non-default ChannelConfig constructor checks maxChunkSize for a minimum value of 8196 but its Javadoc states that is must be grater than or equal 8192. If the check is correct indeed (it was modified intentionally from 8192 in the last commit) doesn't it deserve some comments in the code?

**Comment by kevinherron** [comment]
Yeah the docs should have been updated. In `dev/0.3` branch it's called `MessageLimits` and the docs on the constructor don't exist at all.
