### ISSUE TITLE
Missing ArrayDimensions in EnumStrings

### ISSUE THREAD

**Issue by CB-IT** [eclipse/milo#397]
Hi,
i am setting up a namespace with some Enums as datatypes. 
But calling .setEnumStrings() does not create ArrayDimensions attribute.

UAExpert says: Invalid ArrayType: Expected Array, Received Scalar

I had to do the following:
```java
myEnumTypeNode.getPropertyNode(new QualifiedName(0, "EnumStrings"))
    .ifPresent(p -> {
        p.setArrayDimensions(new UInteger[] {});
    });
```
Maybe it could be included in the SDK. Currently working in dev/0.3

**Comment by kevinherron** [comment]
I think it would be appropriate to review all the optional properties for all the Node types and make sure when the Property nodes are implicitly created they get set up correctly.

Thanks for the report.
