### ISSUE TITLE
请问一下，如何使用证书模式来访问里例如kepserver这类opc服务端

### ISSUE THREAD

**Issue by ewewre** [eclipse/milo#412]
通过自己生成的证书文件并不能进行访问。

**Comment by kevinherron** [comment]
Sorry, unless this gets translated to English I’m afraid there’s nobody to answer.

**Comment by ewewre** [comment]
How to use certificate mode to access OPC servers such as kepserver，
Certificate files generated by oneself are not accessible。

**Comment by kevinherron** [comment]
You certainly can connect to KEPServerEx using self signed certificates.

You'll have to trust Milo's client certificate in the KSE config UI, and then if you have trust the KSE certificate on the Milo side. 

If you're using `DirectoryCertificateValidator` this involves moving the certificate from the `rejected` directory to the `trusted/certs` directory.

**Comment by tandi960505** [comment]
请问你解决了没
