### ISSUE TITLE
Add logging to AnnotationBasedInvocationHandler

### ISSUE THREAD

**Issue by stud0709** [eclipse/milo#413]
Hello Kevin, 

would you please add some logging to the error handling within new Thread in AnnotationBasedInvocationHandler.invoke() (starting from line 180 "catch (InvocationTargetException e) {..."). 

The exception being captured here is not logged, so it is hardly possible to infer the reason of Bad_Internal_Error being generated here.

Thank you!

YDzh

**Comment by kevinherron** [comment]
Done, but in branch `dev/0.3`. I'm not sure there will be another `0.2.x` release.
