### ISSUE TITLE
Server capabilities: LocaleIdArray

### ISSUE THREAD

**Issue by stud0709** [eclipse/milo#420]
Hello Kevin, 

an OPC UA server can support multiple locales (this is why LocaleId is an array). But an UaNode has only one LocalizedText description. 

Is it possible to have multiple locales with milo?

Best Regards, 

Yuriy

**Comment by kevinherron** [comment]
It's not well supported right now. 

You'd have to implement it by intercepting at your `Namespace`'s read() implementation or by setting an `AttributeDelegate` on the UaNode that intercepted calls to read the description.

But it looks like the user's locale ids from `ActivateSession` aren't even set on the `Session` right now, so I think some work will need to happen.

**Comment by kevinherron** [comment]
tracking in #421

**Comment by kevinherron** [comment]
@stud0709 this has been implemented
