### ISSUE TITLE
Gitter Channel for the project

### ISSUE THREAD

**Issue by joesan** [eclipse/milo#458]
Is there a gitter channel for the project? Could you please set one up? I have few questions on some code bits and I think it would be a good idea to clarify such questions on the channel!

**Comment by kevinherron** [comment]
There was but I closed it because I want all questions to be handled on the mailing list. I don’t have time to support the gitter chat as well.

**Comment by joesan** [comment]
I have a question on some code. Should I address it via the user group mailing list?

**Comment by kevinherron** [comment]
Yes, please use the mailing list for questions. I’d like to focus the community there.

**Comment by heywiki** [comment]
Is the closed gitter channel archived somewhere? We linked some of our release notes and documentation to issues described there...

**Comment by kevinherron** [comment]
Not that I'm aware of. I don't know what gitter or GitLab did with closed channels.
