### ISSUE TITLE
Deadlock when disconnecting / closing session

### ISSUE THREAD

**Issue by kevinherron** [eclipse/milo#474]
As reported in #471 

Should be fixed by just upgrading `netty-channel-fsm` to 0.3.

**Comment by drFabio** [comment]
I am still experiencing this behaviour with sdk-client 0.3.8

**Comment by kevinherron** [comment]
I think this is something different, can you open a new issue? It doesn't appear to be a traditional deadlock or the thread dump would have indicated which threads were involved, so it will probably be harder to diagnose.

**Comment by drFabio** [comment]
@kevinherron Done https://github.com/eclipse/milo/issues/614. Please let me know if you need any other info or if you have any insights that could guide me to diagnose it better.

Thanks!
