### ISSUE TITLE
Shouldn't Identifiers class better be an enum ??? 

### ISSUE THREAD

**Issue by mojadita** [eclipse/milo#487]
Why that class has not been implemented as an `enum`? Should it be possible to enumerate the `values()` method or to be able to get the `name()` for display purposes?

**Comment by mojadita** [comment]
Well I can patch it to be an enum if possible.  I know forcing it to be an enum makes it impossible to create `Node`s freely, but probably `Identifier` can include a `Node` reference in it's definition, so the Node is available then.

**Comment by kevinherron** [comment]
I don't think there's a compelling reason to make this change and it would break existing code.

(I do break compatibility between releases, since it's not v1.0 yet, but I try to have a good reason)

**Comment by mojadita** [comment]
My idea was to associate character strings to the enum values, so they can be used as display strings for the user.  Also, being able to iterate all possible supported values would be something useful in several scenarios.  But anyway, an enum can be constructed, incorporating both, the original `Node` value and the display string, so just forget this.
