### ISSUE TITLE
Licensing Question

### ISSUE THREAD

**Issue by gopalakrishnan-subramani** [eclipse/milo#496]
I am very clear about Eclipse Public License, no question on same, thanks for great work on Milo.

I am looking into OPC UA License Agreements, https://opcfoundation.org/license/source/1.11/index.html

OPC Foundation License code has dual license, especially the stack portion.

I see, Milo using OPC UA Foundation code? I see some references [ org.opcfoundation.opcua.binaryschema.FieldType, etc] to the OPC UA binaryschema, wanted to know license terms of the end product developed using Milo's license status. Also I see that this code seems to be generated during build time.

https://github.com/eclipse/milo/blob/master/opc-ua-stack/bsd-parser/bsd-parser-core/src/main/java/org/eclipse/milo/opcua/binaryschema/AbstractCodec.java

When we use Milo's code base to build the OPC UA application, do we inherit a GPL 2.0 license from OPC Foundation?

**Comment by kevinherron** [comment]
The code is generated from an XML schema. I only chose the package name `org.opcfoundation.opcua.binaryschema` to help distinguish it as generated code and hint at the source of the schema. 

You do not have to worry about any licensing issues.
