### ISSUE TITLE
Always build source attachments

### ISSUE THREAD

**Issue by ctron** [eclipse/milo#5]
Currently the build only generates javadoc and source attachments when the "release" profile is active.

I would suggest to always generate the source and javadoc attachments so that it is possible to work with the source code in the case of -SNAPSHOT versions.

**Comment by kevinherron** [comment]
Hmm. Let me see how much longer it takes to build when including javadocs.

I think, if nothing else, I should deploy snapshots with release profile active.

**Comment by ctron** [comment]
Would you just could add some "withDocs" profile. Which does the trick.

**Comment by ctron** [comment]
Thanks :+1: So this gets to deployed to the maven repository then, even for -SNAPSHOT builds?

**Comment by kevinherron** [comment]
You have to activate this profile when you package or deploy, but yes I'll deploy SNAPSHOT builds with javadoc and source now.

locally: `mvn clean install -P javadoc-and-source`
deploying: `mvn clean deploy -P javadoc-and-source` 

I've deployed a version to sonatype that includes javadoc and source.

**Comment by ctron** [comment]
Thanks a lot!
