### ISSUE TITLE
OPC UA CLIENT JAVA APLICATION WRITE PROBLEM

### ISSUE THREAD

**Issue by msamgar** [eclipse/milo#505]
Hello there,
I am trying to write data from Client with OPC UA. I'm using Milo 0.3.1. I cannot write a label that I have successfully read. The type of label I'm trying to write in KepServer is 'Long'. The code I'm trying to write is:
`public void WriteOpcBlocks(OpcRegister[] OpcBlock, Device Device) {
		if(Communicator.OpcClient==null){
			Communicator.Connect();
		}
		for(int i=0;i<OpcBlock.length;i++){
			if(OpcBlock[i]!=null){
				//List<NodeId> nodeIds = ImmutableList.of(new NodeId(Communicator.GetComTypeInfo().GetOpcNodeId(),OpcBlock[i].OpcTagName));
				NodeId nodeIds = new NodeId(Communicator.GetComTypeInfo().GetOpcNodeId(),OpcBlock[i].OpcTagName);
		        
				try {
			            Variant v = new Variant(UInteger.valueOf(5));
			            // don't write status or timestamps
			            DataValue dv = new DataValue(v,null,null);
			            StatusCode status = Communicator.OpcClient.writeValue(nodeIds, dv).get();//statusCodes.get(0);

			            if (status.isGood()) {
			                CommunicationStatus=0;
			            }else{
			            	CommunicationStatus=102;
			            }
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					CommunicationStatus=1102;
					if (Communicator.GetComTypeInfo().GetAccessPointLogFlag()) {
						LogManager.info("Opc Okuma başarısız. Cihaz: " + Device.DeviceDescription + " Tip: " + RequestType + " Tag: " + OpcBlock[i].OpcTagName);
					}
					e.printStackTrace();
				} catch (ExecutionException e) {
					// TODO Auto-generated catch block
					CommunicationStatus=1102;
					if (Communicator.GetComTypeInfo().GetAccessPointLogFlag()) {
						LogManager.info("Opc Okuma başarısız. Cihaz: " + Device.DeviceDescription + " Tip: " + RequestType + " Tag: " + OpcBlock[i].OpcTagName);
					}
					e.printStackTrace();
				}
			}else{
				break;
			}
		}
	}
![Capture](https://user-images.githubusercontent.com/16205108/60248486-6b731d00-98cb-11e9-86e3-eadeb16e524b.PNG)
`

**Comment by msamgar** [comment]
The type is in my UInteger code, but I also tried Ulong. Again, my write operation failed. Error code :
StatusCode {name = Bad_TypeMismatch, value = 0x80740000, quality = bad}
OpcBlock [i] .OpcTagName: ModBus TCP.Powys 1 Phase Current Transformer Ratio
Communicator.GetComTypeInfo (). GetOpcNodeId (): 2

**Comment by msamgar** [comment]
Sorry. OpcBlock [i] .OpcTagName: ModBus TCP.Powys 1 Faz.Akım Trafo Oran

**Comment by msamgar** [comment]
This problem has improved with the following code;
`public void WriteOpcBlocks(OpcRegister[] OpcBlock, Device Device) {
		if(Communicator.OpcClient==null || !Communicator.IsConnectOpc()){
			Communicator.Connect();
			if(Communicator.OpcClient==null || !Communicator.IsConnectOpc()){
				CommunicationStatus=1106;
			}
		}
		for(int i=0;i<OpcBlock.length;i++){
			if(OpcBlock[i]!=null){
				//List<NodeId> nodeIds = ImmutableList.of(new NodeId(Communicator.GetComTypeInfo().GetOpcNodeId(),OpcBlock[i].OpcTagName));
				NodeId nodeIds = new NodeId(Communicator.GetComTypeInfo().GetOpcNodeId(),OpcBlock[i].OpcTagName);
		        
				try {
			            Variant v = new Variant(Integer.parseInt(OpcBlock[i].WriteValueString));
			            System.out.println("start write. val : "+OpcBlock[i].WriteValueString);
			            // don't write status or timestamps
			            
			            DataValue dv = new DataValue(v,null,null);
			            StatusCode status = Communicator.OpcClient.writeValue(nodeIds, dv).get();//statusCodes.get(0);
			            System.out.println("status: " + status.isGood());
			            if (status.isGood()) {
			                CommunicationStatus=0;
			            }else{
			            	CommunicationStatus=1102;
			            }
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					CommunicationStatus=1102;
					if (Communicator.GetComTypeInfo().GetAccessPointLogFlag()) {
						LogManager.info("Opc Okuma başarısız. Cihaz: " + Device.DeviceDescription + " Tip: " + RequestType + " Tag: " + OpcBlock[i].OpcTagName);
					}
					e.printStackTrace();
				} catch (ExecutionException e) {
					// TODO Auto-generated catch block
					CommunicationStatus=1102;
					if (Communicator.GetComTypeInfo().GetAccessPointLogFlag()) {
						LogManager.info("Opc Okuma başarısız. Cihaz: " + Device.DeviceDescription + " Tip: " + RequestType + " Tag: " + OpcBlock[i].OpcTagName);
					}
					e.printStackTrace();
				}
			}else{
				break;
			}
		}
	}`

**Comment by msamgar** [comment]
I haven't tried other data types yet

**Comment by kevinherron** [comment]
Long might just map to Int64 in OPC UA, which would be `new Variant(1L)`

**Comment by kevinherron** [comment]
If you connected and browsed with something like UaExpert you could verify.
