### ISSUE TITLE
BadIdentityTokenInvalid for anonymous user

### ISSUE THREAD

**Issue by stud0709** [eclipse/milo#506]
Hello Kevin,

in ExampleServer.java (v. 0.3.2), if I exclude identityValidator from serverConfig and try to connect to the server using SecurityPolicy: None and Message Security Mode: None as Anonymous, the client gets BadIdentityTokenInvalid error. 

Is this a desired behaviour? I suppose, there should be no identity check in this case...

Used client: UaExpert by Unified Automation

Thank you!

BR,

stud0709

**Comment by kevinherron** [comment]
This is technically the right behavior for what is not really a valid configuration. 

The closest thing to no identity check is to configure an Anonymous access policy.

**Comment by stud0709** [comment]
But USER_TOKEN_POLICY_ANONYMOUS is still defined at line 176.

**Comment by kevinherron** [comment]
Oops, I should have read this more carefully. You still need a validator even with anonymous access policy. The `UsernameIdentityValidator` also handles anonymous identity validation but there's nothing stopping you from creating your own. It's important that a validator exists even for anonymous so an object representing the anonymous identity can be returned.

**Comment by stud0709** [comment]
OK, many thanks :)
