### ISSUE TITLE
Why is OPC UA booting the server very slow?

### ISSUE THREAD

**Issue by NiceWorkBryant** [eclipse/milo#524]
Hello,Why is OPC UA booting the server very slow?The server was started very quickly last week.Can you tell me why? Thank you.

**Comment by kevinherron** [comment]
How long does it take? What version of Milo are you using? Did something change?

It seems to boot fairly quick for me.

**Comment by kevinherron** [comment]
If you have more information about this issue feel free to re-open or ask the mailing list.

**Comment by NiceWorkBryant** [comment]
About 5 minutes.I am using the latest version of milo.I didn't do anything, milo became like this, I feel very strange.I started the milo server on other computers and it is normal.I hope you can help me.thank u.
