### ISSUE TITLE
Created Alarms don't disappear on Alarms tab UAExpert

### ISSUE THREAD

**Issue by AngelThread** [eclipse/milo#539]
Hi,
I have been creating my own alarms as bellow, alarms appear on UA expert as expected but they don't disappear after some time as they are supposed to be. What I am doing is reading all events from another source and conveying it to another OPC UA server. Could you tell me if I am missing a point?

                        AlarmConditionNode eventNodeAlarm = (AlarmConditionNode) server.getServer().getEventFactory().createEvent(
                                new NodeId(1, UUID.randomUUID()),
                                Identifiers.AlarmConditionType
                        );
                        eventNodeAlarm.setActiveState(eventDeserialized.getActiveState());
                        eventNodeAlarm.setBranchId(eventDeserialized.getBranchId());
                        eventNodeAlarm.setConditionName(eventDeserialized.getConditionName());
                        eventNodeAlarm.setEventId(eventDeserialized.getEventId());
                        eventNodeAlarm.setEventType(Identifiers.AlarmConditionType);
                        eventNodeAlarm.setMessage(eventDeserialized.getMessage());
                        eventNodeAlarm.setRetain(eventDeserialized.getRetain());
                        eventNodeAlarm.setSeverity(eventDeserialized.getSeverity());
                        eventNodeAlarm.setSourceName(eventDeserialized.getSourceName());
                        eventNodeAlarm.setTime(eventDeserialized.getUtcTime());
                        eventNodeAlarm.getActiveStateNode()
                                .setValue(new DataValue(new Variant(eventDeserialized.getActiveState())));
                        eventNodeAlarm.setAckedState(eventDeserialized.getAckedState());
![image](https://user-images.githubusercontent.com/15628364/63382382-e708bc00-c39a-11e9-8e11-9775f088bfe9.png)

**Comment by AngelThread** [comment]
Hi,
I have been creating my own alarms as bellow, alarms appear on UA expert as expected but they don't disappear after some time as they are supposed to be. What I am doing is reading all events from another source and conveying it to another OPC UA server. Could you tell me if I am missing a point?

                        AlarmConditionNode eventNodeAlarm = (AlarmConditionNode) server.getServer().getEventFactory().createEvent(
                                new NodeId(1, UUID.randomUUID()),
                                Identifiers.AlarmConditionType
                        );
                        eventNodeAlarm.setActiveState(eventDeserialized.getActiveState());
                        eventNodeAlarm.setBranchId(eventDeserialized.getBranchId());
                        eventNodeAlarm.setConditionName(eventDeserialized.getConditionName());
                        eventNodeAlarm.setEventId(eventDeserialized.getEventId());
                        eventNodeAlarm.setEventType(Identifiers.AlarmConditionType);
                        eventNodeAlarm.setMessage(eventDeserialized.getMessage());
                        eventNodeAlarm.setRetain(eventDeserialized.getRetain());
                        eventNodeAlarm.setSeverity(eventDeserialized.getSeverity());
                        eventNodeAlarm.setSourceName(eventDeserialized.getSourceName());
                        eventNodeAlarm.setTime(eventDeserialized.getUtcTime());
                        eventNodeAlarm.getActiveStateNode()
                                .setValue(new DataValue(new Variant(eventDeserialized.getActiveState())));
                        eventNodeAlarm.setAckedState(eventDeserialized.getAckedState());
![image](https://user-images.githubusercontent.com/15628364/63382382-e708bc00-c39a-11e9-8e11-9775f088bfe9.png)

**Comment by kevinherron** [comment]
I don't know how or when UaExpert decides to remove alarm events from that list. You might need to ask them.

Do make sure you call `delete()` on the event nodes after they've been posted to the event bus, though, or you'll leak memory.

**Comment by AngelThread** [comment]
Thank you for the information. I was thinking maybe it is because of the type of alarm that I am using or I am missing setting a field.

**Comment by juangburgos** [comment]
@UgurYeter did you ever find out what field was missing?
