### ISSUE TITLE
Stopping server won't disconnect clients

### ISSUE THREAD

**Issue by Christiaan676** [eclipse/milo#545]
Calling `shutdown` on the `OpcUaServer` seams to be closing the bind ports correctly and no new connections are accepted, but the connected Opc-UA clients will remain connected. Event if I use the session manager and kill the session it will only generate an error at the client side and reconnect the session.

To be sure is calling shutdown the correct way to completely shut down the server?

**Comment by Christiaan676** [comment]
Yes that way the clients will disconnect and won't be able to reconnect.

Thanks for the quick response!

**Comment by kevinherron** [comment]
Okay. I'll make closing these channels part of shutdown. In the meantime you can close them yourself as a workaround.
