### ISSUE TITLE
Unable to detect which endpoints were successfully bound

### ISSUE THREAD

**Issue by Flofler** [eclipse/milo#548]
Calling `startup` on the `OpcUaServer` doesn't lead to any exception if one of the endpoints could not be bound to their socket. Is there any way to detect which endpoints were successfully bound without reading the log messages?

**Comment by kevinherron** [comment]
Hmm. I'll have to take a look at how the API could be changed to accommodate this in 0.4.0.

**Comment by kevinherron** [comment]
You can now call UaStackServer#getBoundEndpoints() and compare the size of this set to the size of set from your `UaStackServerConfig`. If they differ in size, do `Sets.difference(config.getEndpoints(), boundEndpoints)` to see which ones weren't bound.
