### ISSUE TITLE
Tags in Milo

### ISSUE THREAD

**Issue by jdhanasekar** [eclipse/milo#559]
Hi Milo,
           Is ```Tag``` feature supported in Milo project by default?. If it is not, how to enable the Tag feature. Currently, I have not connected PLC devices with OPC UA Server. Is it possible to share empty Tag values to Client?.

Please help me on this.

Thanks,
Dhanasekar

**Comment by kevinherron** [comment]
This is an SDK that can be used to build an OPC UA server, not an OPC UA server implementation with drivers for any PLCs.

**Comment by jdhanasekar** [comment]
Ok.. I just want to connect to client with Tags. This is for experimental purpose.

In Milo, Tags will available only When drivers for PLCs are present?. Or Milo have dummy Tags ?

**Comment by kevinherron** [comment]
Most demo servers, including the milo example server and the one hosted at milo.digitalpetri.com, have some "dummy" nodes in it that clients can read, write, or subscribe to.

You can also download a "real" OPC server from someone like Kepware and use their 2 hour trial to experiment.

**Comment by jdhanasekar** [comment]
Thanks for the info.

I want to understand the flow of Milo Project. Where do I start from ( I mean file to start) ?.

**Comment by kevinherron** [comment]
[ExampleServer](https://github.com/eclipse/milo/blob/master/milo-examples/server-examples/src/main/java/org/eclipse/milo/examples/server/ExampleServer.java) and [ExampleNamespace](https://github.com/eclipse/milo/blob/master/milo-examples/server-examples/src/main/java/org/eclipse/milo/examples/server/ExampleNamespace.java) are a good place to start for the server.

**Comment by jdhanasekar** [comment]
Ok..I will go through that..
Thanks for guidance..
