### ISSUE TITLE
Automatic-Module-Name needs to be unique for each maven module

### ISSUE THREAD

**Issue by comtel2000** [eclipse/milo#584]
based on #442 please choose a dedicated automatic module name for each maven module (stack-client, stack-core, sdk-client, etc.).

current 'stack-core' MANIFEST.MF:

```
..
Automatic-Module-Name: org.eclipse.milo.opcua
Bundle-License: https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.
 html
Bundle-SymbolicName: org.eclipse.milo.stack-core
Implementation-Version: 0.3.6
..
```
needs to be changed into:
```
..
Automatic-Module-Name: org.eclipse.milo.stack.core
..
```

Just like the Bundle-SymbolicName just with '.' instead of '-'

**Comment by comtel2000** [comment]
or changed to the root package name (stack-core):
```
..
Automatic-Module-Name: org.eclipse.milo.opcua.stack.core
..
```

**Comment by kevinherron** [comment]
I think I'll just use the root package name. Should be able to do this and release it with 0.3.7 this week.

**Comment by comtel2000** [comment]
Thanks, that's really quick :)
