### ISSUE TITLE
ExampleNamespace: CustomDataType does not reveal its internal structure

### ISSUE THREAD

**Issue by stud0709** [eclipse/milo#600]
Hello Kevin, 

if I start ExampleServer, there is a sample of a custom data type. But its internal structure is not shown, only its encoded data is available.

![2020-02-03_10h45_24](https://user-images.githubusercontent.com/31960113/73642618-4b31ea80-4672-11ea-9c6f-9c31d68b2fa6.png)

What can I do to make its internal structure visible? Here is what I need to do:

![2020-02-03_10h23_57](https://user-images.githubusercontent.com/31960113/73642804-a95ecd80-4672-11ea-8be4-119f52965dd4.png)

Here, a Line is an array of m Machines, a Machine is an array of n Win... - Elements and each Win...-Element has its scalar data. 

Thank you!

BR,

stud0709

**Comment by kevinherron** [comment]
There's 2 issues you're seeing here.

1. In 0.3.x custom structures are only readable by clients with advanced knowledge of those structures, unless you use a code modeling tool that also generates the dictionary and then manage to import/create all the nodes represented in the NodeSet2 XML.

In the `dev/0.4` branch this situation has changed and [you can now describe a custom structure and the SDK will generate the dictionary and all the other nodes for you](https://github.com/eclipse/milo/blob/2afe5a42b785ed43a6fa4ce7374ff727ef4d8a2c/milo-examples/server-examples/src/main/java/org/eclipse/milo/examples/server/ExampleNamespace.java#L826-L875), but..

2. Having Nodes in the Address Space that mimic the structure would need to be done entirely yourself, there's no tools or APIs to do that.

**Comment by stud0709** [comment]
I see... that's beyond my skill level :)

Anyway, thank you for the fast reply!

BR,

stud0709
