### ISSUE TITLE
Whether offline reconnection is supported

### ISSUE THREAD

**Issue by xiannvdezhu** [eclipse/milo#629]
Hello! If I disconnect the server from PLC during operation, can I monitor dynamically and reconnect

**Comment by kevinherron** [comment]
I'm not sure I understand your question.

If you're using the client SDK and connecting to an OPC UA server, it will automatically reconnect.

If you're using the server SDK then it's entirely up to you if you're connected to a PLC and whether or not you reconnect to the PLC if it is disconnected. This library has no code for dealing with PLCs, that's just simply one thing OPC UA servers are implemented to model/communicate with.

**Comment by xiannvdezhu** [comment]
okay, thank you.
SDK, do you have any help documents

**Comment by kevinherron** [comment]
> do you have any help documents

Nothing right now beyond the Javadoc on the APIs and the [example projects](https://github.com/eclipse/milo/tree/master/milo-examples) :disappointed:

**Comment by xiannvdezhu** [comment]
strive,
