### ISSUE TITLE
Is it supported opc AE？

### ISSUE THREAD

**Issue by mumugong** [eclipse/milo#640]
I want  to read a alarms & events , Does milo support it?

**Comment by kevinherron** [comment]
Yes, as a client it's just an event subscription:

https://github.com/eclipse/milo/blob/master/milo-examples/client-examples/src/main/java/org/eclipse/milo/examples/client/EventSubscriptionExample.java

https://github.com/eclipse/milo/blob/master/milo-examples/client-examples/src/main/java/org/eclipse/milo/examples/client/EventSubscriptionExampleProsys.java

**Comment by mumugong** [comment]
I want to connect to the local kepware AE ,
,What needs to be done? 
I modify the ClientExample 
 `default String getEndpointUrl() {
        return "opc.tcp://127.0.0.1:49320";
    }`
and receive nothing?

**Comment by mumugong** [comment]
> Yes, as a client it's just an event subscription:
> 
> https://github.com/eclipse/milo/blob/master/milo-examples/client-examples/src/main/java/org/eclipse/milo/examples/client/EventSubscriptionExample.java
> 
> https://github.com/eclipse/milo/blob/master/milo-examples/client-examples/src/main/java/org/eclipse/milo/examples/client/EventSubscriptionExampleProsys.java



> Yes, as a client it's just an event subscription:
> 
> https://github.com/eclipse/milo/blob/master/milo-examples/client-examples/src/main/java/org/eclipse/milo/examples/client/EventSubscriptionExample.java
> 
> https://github.com/eclipse/milo/blob/master/milo-examples/client-examples/src/main/java/org/eclipse/milo/examples/client/EventSubscriptionExampleProsys.java

I want to connect to the local kepware AE ,
,What needs to be done?
I modify the ClientExample
default String getEndpointUrl() { return "opc.tcp://127.0.0.1:49320"; }
and receive nothing?

**Comment by mumugong** [comment]
> Yes, as a client it's just an event subscription:
> 
> https://github.com/eclipse/milo/blob/master/milo-examples/client-examples/src/main/java/org/eclipse/milo/examples/client/EventSubscriptionExample.java
> 
> https://github.com/eclipse/milo/blob/master/milo-examples/client-examples/src/main/java/org/eclipse/milo/examples/client/EventSubscriptionExampleProsys.java

I want to connect to the local kepware AE ,
,What needs to be done?
I modify the ClientExample
default String getEndpointUrl() { return "opc.tcp://127.0.0.1:49320"; }
and receive nothing?

**Comment by kevinherron** [comment]
Kepware’s AE support is OPC Classic only as far as I know. It is not OPC UA Alarms and Conditions.
