### ISSUE TITLE
java 11

### ISSUE THREAD

**Issue by kaoding** [eclipse/milo#649]
**Describe the bug**

java.lang.IllegalAccessException: class io.netty.util.internal.PlatformDependent0$6 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @7d20d0b
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)

**Expected behavior**
A clear and concise description of what you expected to happen instead.

**Logs and Packet Captures**
If applicable, add application logs or Wireshark captures to help explain your problem.

**Additional context**
Version of Eclipse Milo you are using, OPC UA client or software server you are interacting with, etc...

**Comment by kevinherron** [comment]
I believe this is just a warning from the Netty library.

https://stackoverflow.com/questions/57885828/netty-cannot-access-class-jdk-internal-misc-unsafe

https://github.com/netty/netty/issues/7817
