### ISSUE TITLE
“milo-netty-wheel-timer” Thread Doubt

### ISSUE THREAD

**Issue by YW767486516** [eclipse/milo#657]
Hi,
When I use JCONSOLE to check the thread, I find that the waiting number of milo-netty-wheel-timer has been increasing, and the speed is very fast. Could it affect my program?

`Name: milo-netty-wheel-timer
Status: TIMED_WAITING
Total blocked: 0, **total waited: 3,277,651**

Stack trace:
java.base@11.0.4/java.lang.Thread.sleep(Native Method)
app//io.netty.util.HashedWheelTimer$Worker.waitForNextTick(HashedWheelTimer.java:579)
app//io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:478)
java.base@11.0.4/java.lang.Thread.run(Thread.java:834)`

Best Regards

**Comment by kevinherron** [comment]
I don't think this is an issue, but you could ask over in the Netty GitHub issue tracker if you want to be sure.
