### ISSUE TITLE
Potential bug: client.addressSpace.getNodeInstance(nodeId).get() freeze subscriptions

### ISSUE THREAD

**Issue by nacyolsa** [eclipse/milo#664]
In my app I subscribe 4000 of nodes. 
When I added `client.addressSpace.getNodeInstance(nodeId).get()` to my `onSubscriptionValue()` method after some time it freezes app. 
I can say it receives subscription over 10 minutes then it freeze without exception, nothing happens, logging stops. 
Without `client.addressSpace.getNodeInstance(nodeId).get()` works correctly. I noticed that it is not freezing on any particular `nodeId`, it seems random.
I have stopped investigating this because I don't need it anymore but I report this as potential bug. I didn't try with original SubscriptionExample.

**Comment by kevinherron** [comment]
You should be careful not to do anything that blocks (like `getNodeInstance().get()`) and in callbacks as well as ensuring that you catch any Exceptions that might occur. 

I'm guessing you either blocked for a while or indefinitely or threw an uncaught exception while inside the callback.
