### ISSUE TITLE
Rate limit parameters should be configurable

### ISSUE THREAD

**Issue by irahabus** [eclipse/milo#668]

**Comment by kevinherron** [comment]
Can you provide more details?

The parameters used by `RateLimitingHandler` _are_ already configurable, you just have to do it early. 

Did you mean something else?

**Comment by irahabus** [comment]
Is there a way to pass the values via the SDK? 
How do i reach the variables inside ConnectionLimits class from the outside?

**Comment by kevinherron** [comment]
Yes, that will work. 

You just have to make sure to make any changes before the first time the server has been started.

**Comment by irahabus** [comment]
Alright, I will try that. Thanks!
