### ISSUE TITLE
ModelChangeEvent does not trigger a BrowseRequest for the affected NodeId

### ISSUE THREAD

**Issue by achintya-kumar** [eclipse/milo#676]
Hi @kevinherron :)

I'm posting it here so that others may find it useful in the future.
After reading the specification, I found that the **GeneralModelChangeEvent** must be emitted on the Server node as I've done here in the ExampleNamespace. I'm adding a variable-node every 2 seconds, emitting a **GeneralModelChangeEvent** on the _Server_ node and updating the _NodeVersion_ property-node of the object where I'm adding the variables-nodes.
![image](https://user-images.githubusercontent.com/11663480/89838069-99b4ca00-db6a-11ea-874c-2cc8d2c888a4.png)
![image](https://user-images.githubusercontent.com/11663480/89837830-0bd8df00-db6a-11ea-8a8c-83b7685179ec.png)

With the code above, I can see that UaExpert is logging these events as follows:
![image](https://user-images.githubusercontent.com/11663480/89837894-2a3eda80-db6a-11ea-910e-d57d0bab3ccd.png)

However, in a **different server** I'm working with, upon receipt of such events by UaExpert, an automatic rebrowse operation occurs as follows:
![image](https://user-images.githubusercontent.com/11663480/89838020-7722b100-db6a-11ea-9d27-ecdbc658b52f.png)

**The question is**: How can I implement similar behavior using Milo so that an automatic rebrowse operation occurs on the affected node after a **GeneralModelChangeEvent** has been received by UaExpert?

I'm attaching the wireshark-capture from the **different server** where it's working fine. 
[wireshark-dump.zip](https://github.com/eclipse/milo/files/5053778/wireshark-dump.zip)

FYI @Ralfidze

**Comment by kevinherron** [comment]
Can you include a capture of the Milo traffic as well?

**Comment by kevinherron** [comment]
Also - I don't see any Browse requests in the capture from the other server.

**Comment by achintya-kumar** [comment]
@kevinherron 
I performed another capture for both the servers. Here are they:
Milo: [milo.zip](https://github.com/eclipse/milo/files/5053906/milo.zip)
Other server: [other-server.zip](https://github.com/eclipse/milo/files/5053907/other-server.zip)

Thanks! :)

**Comment by kevinherron** [comment]
It looks like you uploaded the same capture for the other server, there's still no browse request present.

**Comment by kevinherron** [comment]
Might not need it though, looks like the SourceNode event field is being reported as `null` in the Milo capture.

**Comment by kevinherron** [comment]
Can you paste your Milo test code into a gist so I can debug it?

**Comment by achintya-kumar** [comment]
I made these changes :)
![image](https://user-images.githubusercontent.com/11663480/89841525-6cb8e500-db73-11ea-9add-87f906b618f8.png)

Here are the captures:
[captures.zip](https://github.com/eclipse/milo/files/5053961/captures.zip)

**Comment by kevinherron** [comment]
What's the Type Definition for the ObjectNode you're adding properties to? `Identifiers.ObjectNode` is not the correct value to use in the `ModelChangeStructureDataType` - that's the only difference I can see from the other server right now.

If it's just a generic `UaObjectNode` you created with no special type definition try `Identifiers.BaseObjectType` instead.

**Comment by kevinherron** [comment]
Oh, also the Verb seems to be different. Try setting the "Reference Added" bit instead.

**Comment by achintya-kumar** [comment]
I made the following change:
![image](https://user-images.githubusercontent.com/11663480/89842773-eef6d880-db76-11ea-920e-422ef3cef826.png)

UaExpert still doesn't seem to be reacting :(
![image](https://user-images.githubusercontent.com/11663480/89842814-09c94d00-db77-11ea-96af-21678dc03db8.png)

Milo capture: 
[milo.zip](https://github.com/eclipse/milo/files/5054035/milo.zip)

**Comment by kevinherron** [comment]
Settings the Reference Added bit would be a `ubyte(4)`, not `ubyte(2)`.

**Comment by achintya-kumar** [comment]
OMG! It works 💯%

Apologies for the error. I was inspired by UnifiedAutomation's documentation of the **ModelChangeStructureDataType**.
![image](https://user-images.githubusercontent.com/11663480/89843542-52820580-db79-11ea-9b85-6e131ed3f930.png)

As usual, thanks again! :D

**Comment by kevinherron** [comment]
Glad it works! I've never attempted this before. 👍
