### ISSUE TITLE
Set target node for events

### ISSUE THREAD

**Issue by achintya-kumar** [eclipse/milo#677]
Hey Kevin @kevinherron :)

I'm working on an example where I can post events on particular nodes of the address-space. 
For example, in **ExampleNamespace** in Milo, I'm trying to post 2 different events to 2 different Object-nodes.
![image](https://user-images.githubusercontent.com/11663480/90080653-72493300-dd0b-11ea-9f35-91d391ef1465.png)

However, upon checking in UaExpert for just one of the 2 Object nodes, I see both the events. Could you please point me to what I'm doing incorrect here?
![image](https://user-images.githubusercontent.com/11663480/90080771-cb18cb80-dd0b-11ea-9392-5ca92910bec9.png)

**Comment by kevinherron** [comment]
Hmm. Doesn’t look like anything is wrong... any chance those 2 Nodes have the same NodeId for some reason?

**Comment by kevinherron** [comment]
I think what you're seeing in the screenshot is that objectAK1 is the EventNotifier, which is different than setting the SourceNode.

If you modified UaExpert to include the SourceNode in the event subscription you'd see that it is correctly sending whatever you set as source.

<img width="844" alt="Screen Shot 2020-08-13 at 6 34 25 AM" src="https://user-images.githubusercontent.com/340273/90140777-109ac000-dd2f-11ea-8905-643e851e1462.png">
<img width="838" alt="Screen Shot 2020-08-13 at 6 34 31 AM" src="https://user-images.githubusercontent.com/340273/90140785-142e4700-dd2f-11ea-955c-fd91db485d80.png">

**Comment by achintya-kumar** [comment]
Thank you for the response :) Please take a look at the following:

I wanted to show you how the 'objectAK' nodes are arranged in the address-space.
As you can see, they are present inside the **HelloWorld** folder. I'm setting the source node as follows:

- _eventNode1_ (with message _AK1 event message!_) to **objectAK1**
- _eventNode2_ (with message _AK2 event message!_) to **objectAK2**

**Goal:** When I subscribe to **objectAK1** in EventView, only the first event (with message _AK1 event message!_) should show up and not the second one.

![image](https://user-images.githubusercontent.com/11663480/90144969-c3930a00-dd7f-11ea-9a43-88527b67e717.png)

![image](https://user-images.githubusercontent.com/11663480/90145061-d7d70700-dd7f-11ea-8441-dab8e45cff95.png)

![image](https://user-images.githubusercontent.com/11663480/90146017-d78b3b80-dd80-11ea-8c25-bffe82be1763.png)

![image](https://user-images.githubusercontent.com/11663480/90146077-ec67cf00-dd80-11ea-8963-1690e1ace3cf.png)

**Comment by kevinherron** [comment]
The problem here likely has to do with your usage of only a single EventBus and your implementation of the `onEventItems...` methods.

To do this correctly, one approach would be to create a separate EventBus associated with each ObjectNode that will act as an event notifier (i.e. it can be subscribed to by a client to receive events). Then, in the `onEventItemsCreated` method, you need to actually pay attention to which ObjectNode is being subscribed to so you can hook up the EventBus associated with that ObjectNode to the EventItems.

**Comment by achintya-kumar** [comment]
Thanks, Kevin! That fixes my problem! :D
