### ISSUE TITLE
Write value return true for "isGood()",but it's not real write success!

### ISSUE THREAD

**Issue by somnuscq** [eclipse/milo#689]
// write asynchronously....
            CompletableFuture<List<StatusCode>> f = client.writeValues(nodeIds, values);
            // ...but block for the results so we write in order
            List<StatusCode> statusCodes = f.get();
            StatusCode status = statusCodes.get(0);// **is need to ensure all statusCodes are good?**
            isGood = status.isGood();

**Comment by kevinherron** [comment]
If the server reports the write succeeded but in reality it didn't then there's nothing you can do from the client side. You should contact the server vendor.

**Comment by somnuscq** [comment]
StatusCode status = statusCodes.get(0);
Do I need to ensure all statusCodes are good when batch writeValues?
Will it happens that  someone of the status is Bad?

**Comment by kevinherron** [comment]
Yes, you should check all of them if you care about the results of the writes. It could happen that some are good and some aren’t.

**Comment by somnuscq** [comment]
Thanks a lot!




            
            
                
                    
                            
                                
                            
                            
                                283451661
                            
                    
                        
                            
                                    邮箱：283451661@qq.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


On 09/04/2020 20:44, Kevin Herron wrote: 
Closed #689.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/eclipse/milo/issues/689#event-3729574676",
"url": "https://github.com/eclipse/milo/issues/689#event-3729574676",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by somnuscq** [comment]
Unfortunately, there is still this problem! KEPServerEX 6 Administration
