### ISSUE TITLE
Best practice to observe the connection state

### ISSUE THREAD

**Issue by tosuns** [eclipse/milo#69]
What would be the best way to observe the state of the client connection ? 
Or better, what would be the best way to notice whether a subscribtion transfer failed after reconnecting to the server and handle the re-subscription of items ?

I notice in my test, that the client retries to connect to the server after the connection gets lost, but fails to transfer the subscribtion because the subscribtion id is not valid anymore to the server (Beckhoff OpcUa Server).

I looked into the code but could not find a convenient way to listen to the connection state. The sdk provides the registration of service fault listener, session and subscribtion listener. I seems like I could use the session and subscribtion listener to build some kind of a state mashine and re-subscribe according to the state, but wanted to know whether the a more convenient way, which I missed to see ?

If there is not such a convenient way to listen to changes to the connection state I would like to suggest to integrate some kind of an connection state listener interface.

**Comment by kevinherron** [comment]
There are two listeners that should provide all the functionality you need.

`OpcUaClient` lets you add a `SessionActivityListener` which notifies you when a session goes active or inactive.

`OpcUaSubscriptionManager` lets you add a `SubscriptionListener`, which among other callbacks has a `onSubscriptionTransferFailed` which is where you should re-subscribe.
