### ISSUE TITLE
Create a first milestone release

### ISSUE THREAD

**Issue by ctron** [eclipse/milo#71]
We should create a first milestone release once the pending CQs are resolved.

**Comment by kartben** [comment]
you don't have to wait for the CQs to all be resolved to do a milestone
release, fwiw

Le lun. 31 oct. 2016 09:56, Jens Reimann <notifications@github.com> a
écrit :

**Comment by ctron** [comment]
That is true. But if something goes wrong, we would need to pull them again. At least that is how I understood it.

**Comment by kevinherron** [comment]
I don't think we'll be doing a milestone release any more - just an actual 0.1.0 in December.
