### ISSUE TITLE
Loading official NodeSets from https://github.com/OPCFoundation/UA-Nodeset

### ISSUE THREAD

**Issue by ebrithiljonas** [eclipse/milo#713]
Is it possible to load NodeSets from the official OPC Foundation [repository ](https://github.com/OPCFoundation/UA-Nodeset) into Milo? And if not, is that feature planned? BEcause it would make it much easier to define types for special cases like the umati standart.

**Comment by kevinherron** [comment]
This is not officially supported yet, but there’s a WIP node set parser and a comment explaining how it can be used here: https://github.com/digitalpetri/opc-ua-nodeset-parser/issues/7#issuecomment-609451277

I do plan to have better support for this in the future.

**Comment by GoetzGoerisch** [comment]
@achintya-kumar could you elaborate one how you did this for us?

**Comment by kevinherron** [comment]
I should clarify: the comment and code I linked to will load a NodeSet XML into an address space, but it does not have anything to do with generating ObjectType or VariableType nodes or struct instances for a given NodeSet. That is a separate concern.

**Comment by ebrithiljonas** [comment]
So basically it is not possible to generate Object- and VariableTypes from an xml file with the current version?

**Comment by kevinherron** [comment]
> So basically it is not possible to generate Object- and VariableTypes from an xml file with the current version?

It's not, and the code generators I am building will not be part of the Milo project. 

They _may_ be open source but I won't decide that until they are done.

**Comment by ebrithiljonas** [comment]
Okey, thank you for the quick replies and the clarification.
