### ISSUE TITLE
Errors when building the project

### ISSUE THREAD

**Issue by noble-man** [eclipse/milo#732]
Hello dear contributors,
I cloned the milo project and executed "mvn clean install" at the root, but it doesn't build.
Could you help me understand the error?
(see maven output attached)
![Screenshot 2020-11-28 at 00 26 48](https://user-images.githubusercontent.com/11802365/100491350-17edaa00-3123-11eb-9bf0-3e95f887b86d.png)
![Screenshot 2020-11-28 at 00 52 49](https://user-images.githubusercontent.com/11802365/100491351-1ae89a80-3123-11eb-8e74-b5a23d125ae3.png)
![Screenshot 2020-11-28 at 00 53 00](https://user-images.githubusercontent.com/11802365/100491352-1c19c780-3123-11eb-8182-761919f0fa46.png)
![Screenshot 2020-11-28 at 00 53 07](https://user-images.githubusercontent.com/11802365/100491355-1cb25e00-3123-11eb-8f41-22284cac99f6.png)

**Comment by kevinherron** [comment]
It seems the tests are taking extraordinarily long to run your computer for some reason.

Can you build successfully if you skip tests?

Try`mvn clean install -DskipTests`

**Comment by noble-man** [comment]
Hi Kevin,
I changed the version in the _pom.xml_ file to _0.5.3_ and it worked.
Thanks
