### ISSUE TITLE
Server methods with custom struct types as arguments return BadInvalidArgument for correct argument

### ISSUE THREAD

**Issue by gjdev** [eclipse/milo#736]
**Describe the bug**
When defining a server method that takes a custom struct type for an Opc Ua Server, the type validation in AbstractMethodInvovationHandler::invoke will not accept an argument of the custom struct type. There is a TODO remark in the code that, when fixed, will probably solve this issue. See https://github.com/eclipse/milo/blob/4d9afff9aeef14a5a6d5c8e552657248835238a0/opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/api/methods/AbstractMethodInvocationHandler.java#L75

**Expected behavior**
When you define a new method in e.g. ExampelNamespace of the example server, and set it up to accept e.g. the CustomStructType as argument, I expect to be able to call the method with a CustomStructType object.

**Additional context**
Using Eclipse Milo 0.5.3 sdk-server, and calling the created method with UaExpert to test it.

**Comment by kevinherron** [comment]
Yes, this will eventually need to be implemented if possible.

In the meantime you can still have methods that use custom structure types as arguments by implementing `MethodInvocationHandler` and decoding and validating the input arguments yourself.
