### ISSUE TITLE
Configuration of OpcUaServer scheduler

### ISSUE THREAD

**Issue by Ashiiro** [eclipse/milo#738]
Hello,

Is it possible for you to make the scheduler in the configuration of the OpcUaServer instead of using the static final field retrieving the scheduler from Stack.

I've tried to figure out something using reflexion but it's not verry safe and it's still impossible to close every ressources that i allocate in a clean way if i open multiple servers.

It is important for me to insulate my different servers (thread wise).

(It is the same for any not configurable ressources taken from the Stack class).

Thank you for this library,
Ashii

**Comment by kevinherron** [comment]
This sounds reasonable, I'll look into changing it.

**Comment by Ashiiro** [comment]
Thank you verry much, do you know when the official 0.5.4 will be released ?

**Comment by kevinherron** [comment]
I will do a release next week when I'm back from vacation. I found a couple other places in the codebase where the executor that gets used is not configurable so I will change those as well.
