### ISSUE TITLE
Provide static instance for AnonymousIdentityValidator

### ISSUE THREAD

**Issue by ctron** [eclipse/milo#74]
What do you think about having a static instance for AnonymousIdentityValidator. As of now this class doesn't hold any state. So we could have

```java
public static final IdentityValidator INSTANCE = new AnonymousIdentityValidator ();
```

And then use it as:

```java
cfg.setIdentityValidator(AnonymousIdentityValidator.INSTANCE);
```

**Comment by kevinherron** [comment]
Seems reasonable. The `OpcUaServerConfigBuilder` creates a default instance of this that it uses if there is never a call to `setIdentityValidator`, so we'd want to point it at this new static instance.
