### ISSUE TITLE
List of implemented OPC UA services

### ISSUE THREAD

**Issue by siGrau** [eclipse/milo#745]
Hi,

I´m new to OPC UA und eclipse milo. I´m wondering if there is a list, which shows all of the OPC UA services currently implemented in eclipse milo.

Thanks in advance

**Comment by kevinherron** [comment]
Here's what _isn't_ implemented:

### Discovery
- FindServersOnNetwork
- RegisterServer
- RegisterServer2

(these are needed by a Discovery Server implementation, which the SDK is not)


The following are not required by the "Standard UA Server" profile but could be implemented by someone using the SDK:

### NodeManagement
- AddNodes
- AddReferences
- DeleteNodes
- DeleteReferences

### View
- RegisterNodes
- UnregisterNodes

### Query
- QueryFirst
- QueryNext

### Attribute
- HistoryRead
- HistoryUpdate
