### ISSUE TITLE
Just some theoretical clarification

### ISSUE THREAD

**Issue by RakshanPremsagar** [eclipse/milo#751]
Hello,
Sorry to be asking this theoretical question here.. needed some clarity over discovery mechanism.
I have a LDS enabled with Multicast extension, running at 4840 port. I also have another server with mDNS enabled running at 4841. Also it is not registered to the LDS yet!
Now, running find Servers on Network, would result in details of both these servers mentioned above.

However, theoretically should it not be the case that the server at 4841 needs to register to the LDSME(port 4840) and only then the server(4841) is discovered?
Because the find Servers On network is always directed to the discovery endpoint right?

Regards and sincere apologies,
Rakshan

**Comment by kevinherron** [comment]
I'm not an expert on the LDS-ME stuff, but it sounds like when you call FindServersOnNetwork against the LDS-ME server on 4840, it is sending a multicast probe and receiving a multicast announcement from the server on 4841, which has sufficient information for the server at 4841 to be returned in the response to FindServersOnNetwork.

<img width="717" alt="image" src="https://user-images.githubusercontent.com/340273/105063380-8880bb00-5a30-11eb-94d4-45de36be6b85.png">

**Comment by RakshanPremsagar** [comment]
Yes thanks Kevin, your statement makes sense. 
But the next sentence of the image you posted explains scenario is seen only when the server uses the register server right? 
![Multicast](https://user-images.githubusercontent.com/50334397/105068600-6cf1d080-5a81-11eb-9b55-ff421b6aa746.png)

**Comment by kevinherron** [comment]
Yes, it does sound like that. I'm not sure how to explain what you're seeing. Who wrote the LDS-ME implementations you are using?

**Comment by RakshanPremsagar** [comment]
It is actually from the open62541 stack. There, generally nobody responds :/
(I am using the code from the examples section -> discovery-> server_lds.c and server_multicast.c)

**Comment by RakshanPremsagar** [comment]
Oh yes, I am running on the same host. Possibly your second sentence is what is occuring in my case.

**Comment by kevinherron** [comment]
I briefly toyed with writing an LDS-ME server using Milo but it never went anywhere. I found the spec to be a little bit lacking in descriptions and examples when it comes to multicast. It's a bit frustrating to work with.

**Comment by RakshanPremsagar** [comment]
I agree!
 Anyway thanks for your response. I will close this issue.
