### ISSUE TITLE
Receiving Bad_TooManyPublishRequests in the Logger

### ISSUE THREAD

**Issue by tosuns** [eclipse/milo#76]
I get a lot of `Bad_TooManyPublishRequests` messages. I want to know what causes this issue ? Do I have to change settings in the milo client, i.e. the subscribtion settings, or do I have to configure the used opc ua server ? How do I avoid this issues or is it not that critical?

**Comment by kevinherron** [comment]
Lower the max pending publish requests when building the client config with `OpcUaClientConfigBuilder#setMaxPendingPublishRequests`.
