### ISSUE TITLE
How to reconnect to the opc server when we lost connection with the opc server ?

### ISSUE THREAD

**Issue by argiraud** [eclipse/milo#832]
Hi,
I'm trying to test if my app reconnect to the opc server when I plug out my app from the network and plug in after 10 seconde. It appears that subscriptions can't be re-create unless I re-run my app. I'm in version 0.6.1.
I saw that normally the re-connection is automatic.
I don't know what I do wrong.

![Sans titre](https://user-images.githubusercontent.com/33487226/116562101-2d017b80-a903-11eb-9f33-23a40bdd4362.png)

**Comment by kevinherron** [comment]
All you need to do is add a `SubscriptionListener` to the `OpcUaSubscriptionManager` and implement `SubscriptionListener::onSubscriptionTransferFailed`. Any time this is called it means the client has reconnected but was unable to resume the session or transfer the old subscription, so you have to re-create it.
