### ISSUE TITLE
how to use the "Sever on Startup" method

### ISSUE THREAD

**Issue by sangjiexun** [eclipse/milo#844]
Hello, SDK developer
  Currently, I am using JavaFX as the UI interface control, the start of the OPC UA service,
  But only closing the service is feasible; opening the service reports the following error:
  (Screenshot)
![image](https://user-images.githubusercontent.com/59449516/119289337-fc500000-bc7c-11eb-8143-8a1e1eca2760.png)
![image](https://user-images.githubusercontent.com/59449516/119296846-54dac980-bc8c-11eb-96d9-2b1965b1707a.png)
![image](https://user-images.githubusercontent.com/59449516/119296904-7936a600-bc8c-11eb-99e1-6e93e30de63f.png)

![bug1](https://user-images.githubusercontent.com/59449516/119290468-21457280-bc7f-11eb-9494-e51d359d440d.png)
![bug2](https://user-images.githubusercontent.com/59449516/119290475-230f3600-bc7f-11eb-8eda-ef0090f3374b.png)
![bug3](https://user-images.githubusercontent.com/59449516/119290476-23a7cc80-bc7f-11eb-8835-98a30b774cd5.png)

**Comment by kevinherron** [comment]
Anything with a startup/shutdown lifecycle is only meant to be started up and shut down once. If you want to start it again then create a new instance of OpcUaServer.
