### ISSUE TITLE
ServiceFault when Deleting Subscriptions

### ISSUE THREAD

**Issue by hutcheb** [eclipse/milo#845]
**Describe the bug**
Prior to closing a session, it is recommended to wait for any outstanding requests to be returned.
https://reference.opcfoundation.org/v104/Core/docs/Part4/5.6.4/

When subscriptions are open we would have to wait for any PublishRequests to be returned which could be a long time depending on the publishinterval/keep alive.  Sending a DeleteSubscriptionsRequest should force the server to return any outstanding PublishRequests with a status code of Bad_NoSubscription.
https://reference.opcfoundation.org/v104/Core/docs/Part4/5.13.8/

**Expected behavior**
There's isn't much description in the spec on what kind of message should be returned for this, at the moment a ServiceFault is returned. As it isn't a fault I would have expected just a PublishResponse with a ServiceResult of Bad_NoSubscription be returned.

**Logs and Packet Captures**
![serivefault](https://user-images.githubusercontent.com/15604556/119337289-a5d2c980-bc5c-11eb-8015-1c98dc12619c.png)

**Additional context**
Milo Server 0.5.4, PLC4X development branch client

**Comment by kevinherron** [comment]
The spec says `ServiceFault` is used any time a service-level error occurs, which I've interpreted as any time the service-level StatusCode being returned is non-good.

**Comment by hutcheb** [comment]
One argument against this would be that it would make the ServiceResult redundant.
I might check other servers just to document it.

**Comment by kevinherron** [comment]
> One argument against this would be that it would make the ServiceResult redundant.

Sure, but the flip side to that argument is that if you can stick a Bad StatusCode into any response that makes ServiceFault redundant.

**Comment by hutcheb** [comment]
I checked four different servers Kepware, open62541, Prosys and python-opcua.

Kepware returns a ServiceFault,
open62541 returns a PublishResponse,
Prosys returns a PublishResponse.
python-opcua doesn't return either.

Doesn't seem to have a standard implementation.

**Comment by kevinherron** [comment]
I’ll make an issue to see if we can get this clarified in the spec.

**Comment by kevinherron** [comment]
@hutcheb Just FYI, I did open an issue for this in the OPC Foundation tracker and the spec is going to be clarified and the Compliance Test Tool updated eventually. Any Bad service result should result in a ServiceFault being returned, not the corresponding response type.

**Comment by hutcheb** [comment]
Hey that's cool, good to get it clarified, thanks for that. :)
