### ISSUE TITLE
is OpcUaClient Thread safe?

### ISSUE THREAD

**Issue by vinodhalaharvi** [eclipse/milo#856]
Is the OpcUaClient thread safe? I noticed when I create a new OpcUaClient, it creates s new TCP client connection to the OpcUa Server. I want some way to multiplex multiple OpcSubscriptions and read/write requests that run on different threads, on a single TCP connection. Is this possible?

**Comment by kevinherron** [comment]
Yes it's thread safe. You can make multiple subscriptions and do concurrent read, write, or any other service calls. There is one TCP connection (and so one secure channel and one session) per `OpcUaClient` instance.

**Comment by vinodhalaharvi** [comment]
thanks @kevinherron !!
