### ISSUE TITLE
Please Update Maven-Snapshots

### ISSUE THREAD

**Issue by Christian-Block** [eclipse/milo#86]
Hello developers,
thank you for your work and publishing an open source version of OPC-UA in JAVA.
I started experimenting with milo today and had some troubles using the client examples. I set up a maven project and added all dependencies described on main page. But it came to errors using the client-examples classes because some methods are missing in the current snapshots. After pulling this repository and packaging it myself it worked. Could you please update the current snapshots or update the README.md .
Thank you :)
Best regards
Christian

**Comment by kevinherron** [comment]
Christian,

There seems to be some problem with the CI server running on the Eclipse
infrastructure that builds and deploys SNAPSHOTs. Thanks for the heads up.
Once we get this fixed there should not be such an issue.
