### ISSUE TITLE
Can't set nodeCache expiration time

### ISSUE THREAD

**Issue by flobz** [eclipse/milo#901]
I would like to change the cache expiration paramater of the nodeCache but it seems impossible.
The constructor set expireAfterWrite to 2 minutes and it can't be changed:
```

public NodeCache() {
        this(b -> {});
    }
    public NodeCache(Consumer<CacheBuilder<Object, Object>> consumer) {
        CacheBuilder<Object, Object> builder = CacheBuilder.newBuilder()
            .expireAfterWrite(2, TimeUnit.MINUTES)
            .maximumSize(16384)
            .recordStats();

        consumer.accept(builder);

        this.cachedNodes = builder.build();
        this.canonicalNodes = new ConcurrentHashMap<>();
    }
```
I can propose a fix if you like.

**Comment by kevinherron** [comment]
Why can't it be changed? Does `CacheBuilder` not allow `expireAfterWrite` to be called a subsequent time?

**Comment by flobz** [comment]
Yes exactly.

**Comment by kevinherron** [comment]
Okay, I see an easy fix that doesn’t break any backwards compatibility.

**Comment by kevinherron** [comment]
See https://github.com/eclipse/milo/pull/902, any objections?

**Comment by flobz** [comment]
No it's perfect! :)

**Comment by flobz** [comment]
Thanks for the quick fix!

**Comment by kevinherron** [comment]
Sure, no problem. I'll have think about actually getting this release out soon, now.
