### ISSUE TITLE
[usability issue] OPCUaServerConfigBuilder has deprecated method without comment on what to do instead. Examples still use deprecated method.

### ISSUE THREAD

**Issue by JonasJurczok** [eclipse/milo#931]
In Milo 0.6.4 there is an [ExampleServer](https://github.com/eclipse/milo/blob/master/milo-examples/server-examples/src/main/java/org/eclipse/milo/examples/server/ExampleServer.java#L168) that we use for test purposes.

In line 168 it uses the setHttpsCertificate.
In this [PR](https://github.com/eclipse/milo/pull/871/files) the method has been deprecated. However there is no comment on what to do instead. And the example server still uses the deprecated method.

To improve usability and lower the entrance barrier can you please
* add a comment on the deprecated method that describes how users of the API should react
* adapt the sample code to make it visible for people reading through the samples.

Thank you

**Comment by JonasJurczok** [comment]
I created a PR to "solve" this. Feel free to use it however you like and/or your rules require you to :)

**Comment by kevinherron** [comment]
Thanks, updated. Be careful using the HTTPS transport, it's not fully implemented or tested. At the time I was working on it I think only the HTTPS + Binary for a client was really being tested, and it was difficult to find other products that had implemented the combination.

**Comment by JonasJurczok** [comment]
Thank you.

And thanks for the heads up. What is the recommended transport?

**Comment by kevinherron** [comment]
The "opc.tcp" transport is the only transport required by all implementations and the only one I've ever seen used in the real world.

**Comment by JonasJurczok** [comment]
Thanks. We will switch to that then :)
