### ISSUE TITLE
Adding value to DataTypeDefinition field of a DataType node

### ISSUE THREAD

**Issue by achintya-kumar** [eclipse/milo#952]
Hi Kevin,

I am working with a custom nodeset specification XML file where there are DataType nodes as follows:
<img width="877" alt="image" src="https://user-images.githubusercontent.com/11663480/160201872-6307dedb-7353-4636-9cb0-954854d9cf80.png">

There are these elements called **Field** therein which have to be parsed. I'm currently using [opc-ua-nodeset-parser](https://github.com/digitalpetri/opc-ua-nodeset-parser) for parsing these XML files. 

I am looking for examples on how to create these fields and set the DataTypeDefinition attribute of the DataType node to look like this:
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/11663480/160201743-bb05f056-912c-400c-9e37-1baaaf963c28.png)

I have tried [this example](https://github.com/eclipse/milo/blob/master/milo-examples/server-examples/src/main/java/org/eclipse/milo/examples/server/ExampleNamespace.java#L824) from the **[server-examples](https://github.com/eclipse/milo/tree/master/milo-examples/server-examples)** module but it doesn't seem to be generating anything on the related node's DataTypeDefinition attribute.

Any help would be very much appreciated.

Thank you!

**Comment by kevinherron** [comment]
Unfortunately `DataTypeDefinition` is a new attribute that was introduced by OPC UA 1.04.

Milo is strictly OPC UA 1.03 right now. I don't think you're going to have any luck with this for now.

The good news is that I've finally started working on OPC UA 1.04 support for what will be Milo 2.0, the bad news is it's probably going to be a while before anything is ready.

**Comment by achintya-kumar** [comment]
@kevinherron Thank you for your reply. All the best. Please let me know if I can also help.
