### ISSUE TITLE
Adding new ReferenceType does not always work

### ISSUE THREAD

**Issue by achintya-kumar** [eclipse/milo#995]
Hi Kevin! 

I am working on adding some ReferenceTypeNode(s) from v1.04 for some experiments. 
I am trying to add the following nodes to the latest version of Milo from master branch:
- HasAddIn
- HasInterface

I started with *HasAddIn* and made the following changes:
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/11663480/168186868-51626e30-457e-4f2b-a532-89dda7ec4a3f.png">

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/11663480/168187071-60b52824-ed8c-4e55-8845-566ff0027274.png">

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/11663480/168187609-0d30e616-6c6a-41a6-9f72-d9c992018c04.png">

With these changes, I rebuilt the project.

---
In order to test, we have a [sample OPC UA server](https://github.com/umati/Sample-Server) implementing v1.04 located here: `opc.tcp://opcua.umati.app:4840`
The node of interest w.r.t. *HasAddIn* is called **BasicGMS** with NodeId `ns=18;i=66382`.

![image](https://user-images.githubusercontent.com/11663480/168192065-cc2c46fa-759a-45f2-9169-e619ff093e2c.png)

---
Now I try to check if the references can be loaded upon browsing the node as follows:
![image](https://user-images.githubusercontent.com/11663480/168192880-b7f979e6-462e-4522-b365-70743616824e.png)

The behavior of the client is exactly as expected, so far.

---

Now comes the ***problematic*** part.
I made the changes to incorporate *HasInterface* ReferenceTypeNode into Milo. The changes made are as follows:
![image](https://user-images.githubusercontent.com/11663480/168193452-a723aa38-36ac-4a64-8e81-6181163a07dc.png)

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/11663480/168193665-485737c1-98d1-4782-974f-90cd279308cd.png">

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/11663480/168193748-bf84b3a9-8a0b-4863-a2fa-3bc6b31f11c5.png">

A project rebuild is thereafter carried out.

---

The node of interest w.r.t. *HasInterface* is called **Identification** with NodeId `ns=18;i=58148`.
![image](https://user-images.githubusercontent.com/11663480/168194970-0721a0d8-e140-4b34-8c7f-e7b9d63173ad.png)

---

Now I try again to check if the references can be loaded upon browsing the node as follows:
![image](https://user-images.githubusercontent.com/11663480/168194483-20988689-8972-4531-b6fc-9a1e787fdac2.png)

The *HasInterface*-type references could not be loaded upon trying to browse NodeId `ns=18;i=58148` despite the fact that the node has 4 of such references. 

I am confused as to why this is happening. Could you please assist me with this?

FYI:

- Milo in use: [link](https://github.com/eclipse/milo/commit/11864af3c6cc85ff5b2daa94e1ac5a03d84aa215)
- OPC UA client: Prosys OPC UA Browser v4.1.2-364

**Comment by kevinherron** [comment]
Hi,

From a quick look at what you’ve sent, it seems the NodeClassMask you are using is only for Variable and Object Nodes, which would exclude the targets of any HasInterface reference.

If that’s not the issue I’ll have to take a closer look on Monday. I’ll be away for the next 3 days.

**Comment by achintya-kumar** [comment]
Thanks as always, Kevin! 
The problem is now resolved. I had a feeling this is caused by the NodeClassMask :)

![image](https://user-images.githubusercontent.com/11663480/168200453-0b7133d9-a466-43bb-af25-cf0c761f59db.png)
